microbiomedata/nmdc-runtime

nmdc_runtime/site/repository.py
nmdc_runtime/site/validation/emsl.py
nmdc_runtime/site/validation/gold.py
nmdc_runtime/site/validation/jgi.py
nmdc_runtime/site/validation/util.py
nmdc_runtime/site/workspace.yaml
requirements/dev.txt
requirements/main.txt
tests/test_util.py

Issue 28: add schema validation to pipeline

---

metadata-translation/notebooks/changesheets-example.ipynb
nmdc_runtime/api/core/metadata.py

Fixes #32 
@dwinston I've tested my code using the `changesheets-example.ipynb`.  I couldn't get your test environment to run on my machine. 
`pytest tests/test_api/test_metadata.py -k item_nested_attr` results in error:
```=============================================== short test summary info ================================================
ERROR tests/test_api/test_metadata.py - dagster.core.errors.DagsterInvalidConfigError: Error in config when building ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Perhaps we can touch base about this tomorrow?

Issue 32: nested objects in array

---

metadata-translation/src/bin/lib/nmdc_data_source.yaml
nmdc_runtime/lib/nmdc_data_source.yaml

@dwinston I found the bug. It had to do with how I was translating data :(   
This merge should fix.

fix biosample but for part of

---

.github/workflows/python-app.yml

Before we were only running tests on pull requests that were looking to
merge with the `main` branch but contributers wanted us to run the tests
on all of them so this change was introduced.

feat(github): run tests on all pull requests

---

metadata-translation/notebooks/data/changesheet-without-separator3.tsv
nmdc_runtime/api/endpoints/metadata.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/validation/util.py
nmdc_runtime/util.py
tests/test_api/test_metadata.py
tests/test_util.py

also, update mongodump for tests

fix: update changesheet input to test to reflect latest schema

---

docs/howto-guides/author-changesheets.md
mkdocs.yml

Add a how-to documentation page on how to author changesheets.
CC: @mslarae13 @cmungall

Documentation for changesheets protocol

---

nmdc_runtime/api/v1/outputs.py

feat(outputs): add client site authentication

---

RELEASES.md
nmdc_runtime/api/endpoints/metadata.py

reverted a mongo search change.

fix(metadata-in): revert returning object in claim

---

RELEASES.md
nmdc_runtime/api/endpoints/util.py

We were returning the wrong type in job claims causing an internal server error

fix(utils): fix change to claim job return

---

RELEASES.md
components/nmdc_runtime/workflow/spec.py
components/nmdc_runtime/workflow_execution_activity/core.py
nmdc_runtime/api/boot/object_types.py
nmdc_runtime/api/boot/triggers.py
nmdc_runtime/api/boot/workflows.py
nmdc_runtime/api/db/mongo.py
nmdc_runtime/api/main.py
nmdc_runtime/api/v1/workflows/activities.py
requirements/main.txt
setup.py

The activities endpoint was needlessly complex. Now it sends back a list of job ids for users to claim instead of object ids for them to search.
update release

add triggers and claiming to activities endpoint

---

components/nmdc_runtime/workflow_execution_activity/core.py
nmdc_runtime/api/v1/workflows/activities.py

Let the activities endpoint handle insertion

Add job db insertion and creation to activities endpoint

---

nmdc_runtime/api/core/metadata.py
nmdc_runtime/api/db/mongo.py
nmdc_runtime/api/endpoints/metadata.py
nmdc_runtime/api/main.py
tests/test_api/test_db_mongo.py
tests/test_api/test_endpoints.py

source from nmdc schema and compatible non-system collections
part of #240

fix: ensuring indexes on 'id'

---

nmdc_runtime/site/translation/submission_portal_translator.py

Just a small fix for something that was initially missed when working on https://github.com/microbiomedata/issues/issues/224

Use samp_name slot from submission portal to also populate name of Biosample

---

nmdc_runtime/util.py
tests/test_api/test_endpoints.py

fix: no 500 error on @type Database or unknown collection

---

nmdc_runtime/api/endpoints/ids.py
nmdc_runtime/api/main.py

feat: rm /ids/* routes (superceded by /pids/*)

---

.github/workflows/release-to-spin.yml

feat: continuous delivery

---

nmdc_runtime/api/endpoints/nmdcschema.py

API method for obtaining collection names

---

nmdc_runtime/api/endpoints/nmdcschema.py
nmdc_runtime/api/endpoints/util.py
nmdc_runtime/api/models/util.py
nmdc_runtime/util.py

feat: mongodb projection for list_resources/ListRequest
closes #280

Implement projection for the API 

---

nmdc_runtime/api/endpoints/util.py

fix: check user-supplied filter for processability

---

RELEASES.md
demo/metadata_migration/from_7_7_2_to_7_8_0/.gitignore
demo/metadata_migration/from_7_7_2_to_7_8_0/.notebook.env.example
demo/metadata_migration/from_7_7_2_to_7_8_0/migrate_7_7_2_to_7_8_0.ipynb
requirements/main.in
requirements/main.txt

In this branch, I manually edited the `requirements/main.in` file so it says `nmdc-schema==7.8.0`, then I ran `$ make update-deps` to update the `requirements/main.txt` file accordingly.
I also documented the associated MongoDB data migration process in the form of a Python notebook.

Update `nmdc-schema` package from `7.7.2` to `7.8.0`

---

nmdc_runtime/api/endpoints/sites.py

Convert API endpoint to a no-op and omit from Swagger UI

---

nmdc_runtime/api/endpoints/objects.py

support desired CURIE resolutions via existing config

---

requirements/dev.txt
requirements/main.in
requirements/main.txt

CC: @dwinston, @turbomam, @Shalsh23, @shreddd

Update `nmdc-schema` from `7.8.0` to `8.0.0`

---

.gitignore
docs/explanation/domain-vision-statement.md
docs/stylesheets/extra.css
mkdocs.yml
nmdc_runtime/api/analytics.py
nmdc_runtime/api/main.py

kicked off by https://github.com/microbiomedata/nmdc-schema/pull/85#issuecomment-1737749889

Log incoming HTTP requests (analytics) and add domain vision statement (docs)

---

nmdc_runtime/util.py

Avoid attempt to fetch large (>16mb) list of distinct IDs, a limitation of collection.distinct(). 
Use aggregation pipeline instead to compute on mongo server, using disk if necessary.
/cc @shreddd

fix: mongo limit wrt `distinct`

---

nmdc_runtime/api/core/auth.py
nmdc_runtime/api/models/capability.py
nmdc_runtime/api/models/id.py
nmdc_runtime/api/models/job.py
nmdc_runtime/api/models/metadata.py
nmdc_runtime/api/models/object.py
nmdc_runtime/api/models/object_type.py
nmdc_runtime/api/models/operation.py
nmdc_runtime/api/models/query.py
nmdc_runtime/api/models/run.py
nmdc_runtime/api/models/util.py
nmdc_runtime/api/models/workflow.py
nmdc_runtime/api/v1/models/ingest.py
nmdc_runtime/infrastructure/database/impl/mongo/models/user.py
nmdc_runtime/minter/domain/model.py
nmdc_runtime/util.py

run `bump-pydantic nmdc_runtime` and apply, plus @model_validator refactor
closes #343 via #339

migrate to pydantic v2

---

nmdc_runtime/api/endpoints/util.py

re-submission of "same" changes is a valid use case
closes #340

fix: de-duplicate metadata submission after one minute

---

nmdc_runtime/api/endpoints/nmdcschema.py

add typecodes enpoint

---

.github/workflows/build-and-release-to-spin.yml

Do full depth checkout so setuptools-scm can detect version

---

.github/workflows/build-and-release-to-spin.yml

Actually push the docker image, but not if running in a fork

---

.github/workflows/build-and-release-to-spin.yml

Fix use of boolean var

---

.github/workflows/build-and-release-to-spin.yml

Env context only available in `steps.if`

---

.dockerignore
nmdc_runtime/api/main.py

Update .dockerignore to ensure "clean" in-container git working directory

---

nmdc_runtime/api/endpoints/objects.py

feat: redirect to data portal landing pages for sty-, bsm-

---

requirements/dev.txt
requirements/main.in
requirements/main.txt

- Manually edited `main.in` (changed the `nmdc-schema` version from `9.2.0` to `9.3.1`)
- Ran `make update-deps` to synchronize `dev.txt` and `main.txt` accordingly

Update `nmdc-schema` package from `9.2.0` to `9.3.1`

---

nmdc_runtime/api/endpoints/util.py

closes #414
...but nmdc schema collections should have an `id` field.

fix: GET /nmdcschema/functional_annotation_agg

---

.env.example
nmdc_runtime/api/core/auth.py
nmdc_runtime/api/endpoints/users.py
nmdc_runtime/api/main.py

For https://github.com/microbiomedata/nmdc-runtime/issues/445

Rename env vars to ORCID_NMDC_CLIENT_{ID,SECRET} 

---

nmdc_runtime/api/endpoints/users.py

feat: get plaintext orcid jwt via cookie

---

requirements/main.in
requirements/main.txt

Upgrade to latest `nmdc-schema` before upcoming release.

Upgrade to nmdc-schema 10.2.0

---

requirements/dev.txt
requirements/main.txt

Updates dependencies via `make update-deps`
Fixes merge conflicts for https://github.com/microbiomedata/nmdc-runtime/pull/550

update requirements for main

---

tests/files/nmdc_bsm-12-7mysck21.json
tests/test_api/test_endpoints.py
tests/test_api/test_metadata.py

This PR makes changes to test_endpoints.py to fix tests that are failing including a biosample test  and a ReadQCAnalysis test for the berkeley branch.
Fixes # https://github.com/microbiomedata/nmdc-runtime/issues/580
I've not done this before for this repo.
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended to be a comprehensive checklist. Consciously decide the applicability of value-added …

`berkeley`: Update `test_endpoints.py` to fix some failing tests

---

requirements/main.in
requirements/main.txt

Upgrade to `nmdc-schema==10.6.0`

Upgrade to nmdc-schema 10.6.0

---

nmdc_runtime/site/export/ncbi_xml.py
tests/test_data/test_ncbi_xml.py

Updates to SRA `<Action>` blocks in NCBI XML

---

requirements/main.in
requirements/main.txt

Upgrade to `nmdc-schema==10.7.0`

Upgrade to nmdc-schema 10.7.0

---

Makefile
docker-compose.test.yml
docs/nb/bulk_validation_referential_integrity_check.ipynb
nmdc_runtime/api/db/mongo.py
nmdc_runtime/api/endpoints/nmdcschema.py
nmdc_runtime/config.py
nmdc_runtime/util.py
tests/mongorestore-nmdc-testdb.sh
util/mongodump-nmdc.sh
util/mongorestore-nmdc.sh

This is a refactored referential-integrity-checker prototype notebook based on requested documentation. In many cases where justification for a decision was requested, the justification was deemed to be historical and no longer applicable, prompting a refactor.
Careful review is requested.
Fixes # 604

feat: refactor notebook and supporting code

---

nmdc_runtime/site/export/ncbi_xml.py
tests/test_data/test_ncbi_xml.py

Make `<DataType>` in NCBI XML SRA `<Action>` block more specific: `generic-data` -> `fastq`
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended to be a comprehensive checklist. Consciously decide the …

Make `<DataType>` in NCBI XML SRA `<Action>` block more specific

---

README.md

In this branch, I documented my expectations around merging the `main` branch into the `berkeley` branch over time.
Fixes #626 
- I read it back to myself.
**Configuration Details**: Open the `README.md` file on the `berkeley` branch.

Document expectations regarding merging `main` into `berkeley` over time

---

Makefile
docker-compose.test.yml
nmdc_runtime/site/translation/gold_translator.py
nmdc_runtime/site/translation/neon_utils.py
nmdc_runtime/site/translation/submission_portal_translator.py
tests/test_api/test_endpoints.py
tests/test_data/test_gold_translator.py
tests/test_data/test_submission_portal_translator.py
tests/test_data/test_submission_portal_translator_data.yaml
tests/test_graphs/test_submission_portal_graphs.py
tests/test_ops/test_materialize_alldocs.py

Changes from the Berkeley schema resulted in a number of test failures, mostly due to missing "type" fields, which are required in the Berkeley schema.
Three remaining tests are failing. These have been skipped for now in order to unblock the CI pipeline. They will be spun into separate GH issues. 
Fixes #  https://github.com/microbiomedata/nmdc-runtime/issues/600
Ran docker commands for testing (see Makefile)

Fix Failing Tests in Berkeley Branch

---

nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/repository.py
nmdc_runtime/site/translation/submission_portal_translator.py
tests/test_data/test_submission_portal_translator.py
tests/test_data/test_submission_portal_translator_data.yaml
tests/test_graphs/test_submission_portal_graphs.py

These changes remove the pytest `xfail` marker on the `test_get_dataset` test function in `tests/test_data/test_submission_portal_translator.py`. Or, to put it another way, these changes are about putting the final (hopefully) touches on getting the `SubmissionPortalTranslator` class working.
Fixes #655 
I ran the complete test suite against the `berkeley` branch as it stands today and again in this branch. The diff of the test summary was:
```diff
< ==================================== 3 failed, 79 passed, 9 skipped, 10 xfailed, 1 xpassed, 3 warnings, 7 errors in 66.26s (0:01:06) ====================================
---
> ==================================== 3 failed, 80 passed, 9 skipped, 9 xfailed, 1 xpassed, 3 warnings, 7 errors in 67.78s (0:01:07) …
```

`berkeley`: Complete conversion of `SubmissionPortalTranslator`

---

nmdc_runtime/site/repository.py
nmdc_runtime/site/translation/submission_portal_translator.py

This PR seeks to migrate the Submission Portal translator for it to work with the berkeley schema.

Migration of submission portal translator to be conformant with berkeley schema

---

nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/repository.py
nmdc_runtime/site/translation/gold_translator.py
tests/test_data/test_gold_translator.py

Updating the GOLD translator to work with the berkeley schema.

Update GOLD translator to work with Berkeley schema

---

demo/metadata_migration/notebooks/migrate_10_8_0_to_11_0_0.ipynb

In this branch, I fixed some bugs in the Berkeley migration notebook. I also bumped the `nmdc-schema` version (used by the notebook) up to `v11.0.0rc22`, which is the latest release available as of today.
- Fixes #670
- Fixes #671 
- Fixes #673

Fix bugs in Berkeley migration notebook and update its `nmdc-schema` version

---

tests/test_ops/test_gold_api_ops.py

This PR seeks to fix the 4 tests that are erroring out in `tests/test_ops/test_gold_api_ops.py`
* `test_gold_biosamples_by_study`
* `test_gold_projects_by_study`
* `test_gold_analysis_projects_by_study`
* `test_gold_study`
Fixes #678 
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template …

Quick fixes for GOLD API client tests in `tests/test_ops/test_gold_api_ops.py`

---

docs/nb/bulk_validation_referential_integrity_check.ipynb

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Replace `# (issue)` below with a reference to the issue that this PR addresses, of the form `#\d+`. If merging this PR should close the issue, use `Fixes` or `Closes`. Then delete this paragraph.
Fixes # (issue)
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting …

576 berkeley updates ref integrity notebook

---

nmdc_runtime/api/endpoints/find.py

In this branch, I updated the name of a field used in a database query, to be consistent with the [Berkeley schema](https://microbiomedata.github.io/berkeley-schema-fy24/associated_studies/) (instead of the legacy schema). This fixes #689.
While I was there, I also updated the docstring to say that the function returns data objects as opposed to data object IDs.

Update field name to be consistent with Berkeley schema

---

.github/workflows/python-app.yml
demo/metadata_migration/notebooks/migrate_10_8_0_to_11_0_0.ipynb

In the `main` branch, I reconfigured GitHub Actions so that developers can trigger the GHA workflow that runs `pytest`, manually via the GitHub web GUI. 
I didn't realize the same configuration would have to exist on the branch I want to utilize that new capability on (as shown here).
So, I've created _this_ PR to get that configuration onto the `berkeley` branch, which _is_ the branch I want to utilize that new capability on.
> [!NOTE]  
> The source branch of this PR (`main`) is frozen. We made an exception to its frozen-ness in order to reconfigure GitHub Actions.

Merge `main` into `berkeley` (routine, September 27, 2024)

---

nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/repository.py
nmdc_runtime/site/translation/neon_benthic_translator.py
nmdc_runtime/site/translation/neon_soil_translator.py
nmdc_runtime/site/translation/neon_surface_water_translator.py
nmdc_runtime/site/translation/neon_utils.py
tests/test_data/test_neon_benthic_data_translator.py
tests/test_data/test_neon_soil_data_translator.py

This PR seeks to migrate the remaining 3 translators that haven't been "migrated" to be conformant with the berkeley schema:
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended to be a comprehensive checklist. …

Migrate NEON translators to be conformant with berkeley schema

---

metadata-translation/notebooks/data/changesheet-array-item-nested-attributes.tsv
metadata-translation/notebooks/data/changesheet-update-pi-websites.tsv
metadata-translation/notebooks/data/changesheet-without-separator3.tsv
tests/files/study_no_credit_associations.json
tests/test_api/test_metadata.py

This PR coverts 3 skipped tests to passing tests in test_metadata.py. This is work coming from the monthly hackathon.
It is not clear to me if we can remove test_update_01 instead of skip it as it seems redundant with the other passing changesheets tests. Hoping @dwinston  can comment on that but fixing it is outside the scope of this PR.
Fixes # (issue)
tests run by gitlab
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the …

Unskip and fix 3 tests that were being skipped in `test_metadata.py`

---

requirements/main.in
requirements/main.txt

Note: no other dependencies updated
Update to latest schema release for hotfix

Bumped up nmdc-schema to v11.0.3

---

docker-compose.test.yml
docker-compose.yml

cleanup: remove obselete `version` attribute

---

.env.example
.env.test
README.md

Accommodate `INFO_BANNER_INNERHTML` default

fix: update .env load guidance

---

.github/pull_request_template.md

In this branch, I updated the PR template in ways I thought would make the resulting PR descriptions easier for people to consume.
The PR template previously began with instructions that I think many developers (including me) did not fully read each time they created a PR; and, as a result, those instructions (some of which say, effectively, "delete me after doing what I say") would remain in the final PR description. This decreased the signal-to-noise ratio for PR reviewers. Also it sometimes made it difficult for reviewers or passersby to determine—at a glance—whether the author actually _filled out_ the template to make a PR description, or just submitted _the template, itself_ as the PR description. This was my main motivation for overhauling the PR template.
In this branch, I took …

Update PR template to produce PR descriptions that are easier to read

---

.github/pull_request_template.md

In this branch, I updated the PR template so its "Subsystem" menu includes "Translators" as an option.
The "translators" I'm referring to are the metadata ingest pipelines, which I think are all in `nmdc_runtime/site/translation` and are, for the most part, maintained by @sujaypatil96.
Fixes #767
PR template.
I'll test them next time I create a PR (once this branch has been merged into `main`).
I don't think there's any documentation coupled with our PR template; other than that which is in the PR template, itself.

Add "Translators" subsystem as option in PR template

---

setup.py

In this branch, I removed the final reference to the recently-deleted directory named `tests2`.
The `tests2` directory was deleted via https://github.com/microbiomedata/nmdc-runtime/pull/784.
Fixes #791 
I'll leave that to the GitHub Actions workflow that will process this branch once I create this PR.

Remove reference to nonexistent `tests2` directory

---

nmdc_runtime/site/export/ncbi_xml.py
nmdc_runtime/site/export/ncbi_xml_utils.py
nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
tests/test_data/test_ncbi_xml.py

This PR seeks to address the following concerns:
* During the "migration" of the export pipeline to work with the berkeley schema, I had forgotten to make adjustments to handle _instrument_used_ correctly
* Formatting of BioProject reference/block in SRA `<Action>` blocks
* `elev` slot needs special handling to add _m_ as unit to it
...
...

Post berkeley schema NCBI export pipeline updates

---

db/migrations/notebooks/migrate_11_1_0_to_11_2_1.ipynb

In this branch, I updated the destination schema version of a migration notebook.
Previously, the notebook used `nmdc-schema` version 11.2.0. That schema version was [not released properly](https://github.com/microbiomedata/nmdc-schema/issues/2300). Version 11.2.1 was released properly and is what I updated this notebook to use.
Fixes #826 
I tested these changes by running the notebook against the shared dev environment earlier today.

Update migration notebook's destination `nmdc-schema` version to 11.2.1

---

nmdc_runtime/site/resources.py
nmdc_runtime/site/translation/gold_translator.py
tests/test_data/test_gold_translator.py
tests/test_ops/test_gold_api_ops.py

In this PR, we are updating `nmdc_runtime/site/translation/gold_translator.py` to accommodate the global filtering criteria, i.e., we need to constrain the list of biosamples that need to be processed (from GOLD) to only those that have `sequencingStrategy == "Metagenome" or "Metatranscriptome"`
...
Fixes https://github.com/microbiomedata/nmdc-runtime/issues/789
* https://github.com/microbiomedata/issues/issues/909
...

Filter biosamples/projects/analysis projects based on `sequencingStrategy`

---

docs/howto-guides/claim-and-run-jobs.md
docs/howto-guides/jobs/gold-translation-etl.md

closes #820
closes #821
I tested these changes by manual inspection (of links and of the docs build logs).

Fix project documentation links

---

.github/workflows/deploy-redirects.yml
.github/workflows/mkdocs.yml

In this branch, I updated a GHA workflow and create a GHA workflow. Both changes are related to the new documentation website, at https://docs.microbiomedata.org.
I updated the GHA workflow that used to build and deploy a MkDocs site to GitHub Pages, so that it no longer deploys it.
I created a GHA workflow that builds a website file tree consisting of web pages that contain only redirects. Each web page will redirect the client to a relevant web page on the new documentation website.
For example, if someone were to visit https://microbiomedata.github.io/nmdc-runtime/, they would be redirected to https://docs.microbiomedata.org/runtime/.
Similarly, if someone were to visit https://microbiomedata.github.io/nmdc-runtime/nb/get_data/, they would be redirected to …

Update GHA workflows to deploy redirects instead of MkDocs site

---

docs/nb/general_usage.ipynb

On this branch, I created a Python notebook demonstrating general usage of the Runtime API.
You can see the rendered version of the notebook at: https://github.com/microbiomedata/nmdc-runtime/blob/862-docs-create-python-notebook-demonstrating-general-use-of-nmdc-runtime-api/docs/nb/general_usage.ipynb
The Python notebook demonstrates three main things:
- Accessing a public API endpoint
- Getting an access token for use with private API endpoints
- Accessing a private API endpoint
Fixes #862 
I tested these changes by running the notebook locally.

Create Python notebook demonstrating general usage of Runtime API

---

.github/workflows/deploy-redirects.yml
docs/nb/api_access_via_python.ipynb

On this branch, I fixed some typos in a Python notebook in the `docs/nb` directory.
I also reset the execution counts in the notebook. I also elaborated on a comment about creating redirects in a GHA workflow.
Fixes #867 
I tested them by reading them to myself early in the day and using an Apple Watch to monitor my heart rate.

Fix typos in Python notebook (in `docs/nb` directory)

---

.github/pull_request_template.md

~In~ **On** this branch, I changed this sentence in the PR template.
I changed it to say "On this branch" instead of "In this branch".
Fixes #868 
I tested these changes by reading both versions and acknowledging that I prefer the "On this branch" one.

Clarify example sentence in PR template

---

db/migrations/notebooks/mongosh-scripts/restore-privileges.mongo.js

On this branch, I updated the MongoDB script that the migration notebooks use to restore users's original permissions after a migration. 
I updated it so that it no longer restores access to a collection that no longer exists (i.e., the `metap_gene_function_aggregation` collection).
Fixes #854 
I will test them when I perform a migration in the development environment next. 🤠

Remove reference to non-existent MongoDB collection (`metap_gene_function_aggregation`)

---

docs/howto-guides/minting-ids.md
mkdocs.yml

On this branch, I added a how-to guide to the Runtime documentation. The guide is about using the Runtime's Swagger UI to mint an ID.
You can view the rendered how-to guide here: https://github.com/microbiomedata/nmdc-runtime/blob/892-make-python-notebook-demonstrating-the-id-minting-process/docs/howto-guides/minting-ids.md
This is a how-to guide I expect some NMDC team members to use within the next few weeks, when creating IDs for studies/parent studies.
Fixes #892 
I tested these changes by performing the steps as I was documenting them.

Write how-to guide about minting IDs via the NMDC Runtime API Swagger UI

---

db/migrations/notebooks/migrate_11_2_1_to_11_3_0.ipynb
db/migrations/notebooks/migrate_11_3_0_to_11_4_0.ipynb

On this branch, I created a Python notebook we will be able to use to migrate the database from `nmdc-schema` `v11.3.0` ([released](https://github.com/microbiomedata/nmdc-schema/releases/tag/v11.3.0) January 17, 2025) to `v11.4.0` ([released](https://github.com/microbiomedata/nmdc-schema/releases/tag/v11.4.0) February 12, 2025).
The notebook will run this migrator: [migrator_from_11_3_0_to_11_4_0.py](https://github.com/microbiomedata/nmdc-schema/blob/main/nmdc_schema/migrators/migrator_from_11_3_0_to_11_4_0.py)
Fixes #890 
I confirmed I could run the cells that contain:
```jupyter
%pip install nmdc-schema==11.4.0
```
```py
MIGRATOR_MODULE_NAME = "migrator_from_11_3_0_to_11_4_0"
migrator_module = importlib.import_module(f".{MIGRATOR_MODULE_NAME}", package="nmdc_schema.migrators")
Migrator …
```

Create notebook that migrates database from `nmdc-schema` v11.3.0 to v11.4.0

---

Makefile
requirements/dev.txt
requirements/main.in
requirements/main.txt

On this branch, I updated the `nmdc-schema` package from version 11.3.0 to 11.4.0 and synchronized the transitive dependencies.
I did not, however, "[try to upgrade all dependencies to their latest versions](https://pip-tools.readthedocs.io/en/latest/cli/pip-compile/)." In other words, I omitted the `--upgrade` option from the `pip-compile` commands. I did that because, when I _included_ that option, Dagster was getting updated to a new minor version that included some breaking changes (I noticed this when the automated tests run by GHA failed on this branch). I want to defer that update until after the upcoming NMDC Release.
**Important:** I do not want this to be merged into `main` until the database has been migrated accordingly (which I'll do on Friday). I would like for it to be …

Bump `nmdc-schema` from `11.3.0` to `11.4.0`

---

nmdc_runtime/site/repository.py
nmdc_runtime/site/translation/neon_benthic_translator.py
tests/test_data/test_neon_benthic_data_translator.py

The PR updates the code in the NEON benthic water translator to account for creating Manifest / `manifest_set` records for samples that have been sequenced multiple times. It also pulls NEON data from the latest/provisional release to update/create new `DataGeneration` and `DataObject` records for samples that were "ignored" in the first ingest.
...
Fixes https://github.com/microbiomedata/issues/issues/1066

Account for multiple sequencing runs in NEON benthic water translator code

---

requirements/dev.txt
requirements/main.in
requirements/main.txt
tests/__init__.py

On this branch, I updated the `nmdc-schema` dependency version from 11.4.0 to 11.5.1. I also updated all other direct dependencies that had updates available, and then synchronized transitive dependencies. I did all of that by editing the `nmdc-schema` line in `main.in` and then running `$ make update-deps`. Technically, I ran it in a Docker container, like this:
```sh
docker compose run --rm --no-deps fastapi sh -c 'make update-deps'
```
Finally, I updated a reference to a Dagster-related class that no longer exists in the new version of Dagster. I also added documentation about that reference.
No additional details.
Fixes #929 
I ran `make test` locally and confirmed all tests passed.

Bump `nmdc-schema` version from `11.4.0` to `11.5.1`

---

README.md
docs/admin.md
docs/howto-guides/release-process.md
docs/howto-guides/update-sensors-ops.md
docs/nb/bulk_validation_referential_integrity_check.ipynb
docs/nb/wf_automation.ipynb
docs/tutorials/json.md

On this branch, I fixed typos, some broken links, and some obsolete examples in the Runtime documentation.
The typos were spelling errors that were reported by the (under construction) spell checker that runs in the `docs` repo (as a reminder, the `docs` repo pulls the Runtime documentation source files from this repo).
The broken links were reported by the link checker that runs in the `docs` repo. Those broken links are listed here: https://github.com/microbiomedata/docs/issues/212. Note that some of the broken links listed on that page were not fixed via this PR. That's because fixing them would require more time than I wanted to spend today. Also, I will likely involve another Runtime developer when fixing those particular broken links, due to their subject matter.
The obsolete …

Fix typos, some broken links, and some obsolete examples in Runtime documentation

---

mkdocs.yml

On this branch, I swapped the icons used for "Switch to dark mode" and "Switch to light mode" with one another. Now, the icon reflects the CURRENT state of a light switch (not the NEXT state).
The light is on (`main` in back, this PR branch in front):
The light is off (`main` in back, this PR branch in front):
Now, flipping the light switch ON turns ON the light (i.e. makes the page bright) and flipping the light switch OFF turns OFF the light (i.e. makes the page dark).
I did not create an issue for this.
I tested these changes locally.

Swap light/dark mode toggler icons to reflect turning on light (docs)

---

nmdc_runtime/site/translation/gold_translator.py

On this branch, we are updating the GOLD translator to start pulling in the field value for `ncbiBioProjectAccession` GOLD API field and assert it on `insdc_bioproject_identifiers` on `nmdc:NucleotideSequencing`.
Fixes https://github.com/microbiomedata/nmdc-runtime/issues/963

assert `insdc_bioproject_identifiers` on DataGeneration records

---

Makefile

Remove obsolete ssh tunnel mapping

---

db/migrations/notebooks/migrate_11_6_0_to_11_6_1.ipynb
db/migrations/notebooks/migrate_11_6_1_to_11_7_0.ipynb

On this branch, I created a Python notebook that runs the `nmdc-schema` `11.6.1`-to-`11.7.0` migrator.
This is the usual copy/paste/modify of our standard migration notebook.
Fixes #982
I used the notebook to perform a "test" migration against a local Mongo server.
Note: the cell that executes the migrator took **55 seconds** to run on my laptop, using a local Mongo server running in a Docker container. This may be of interest to whoever is scheduled to drive the next NMDC Release (it's me).

Create Python notebook that runs `nmdc-schema` `11.6.1`-to-`11.7.0` migrator

---

requirements/dev.txt
requirements/main.in
requirements/main.txt

On this branch, I updated the version of `nmdc-schema` that the Runtime uses, from 11.6.1 to 11.7.0.
To do this, I updated `main.in` manually...
```diff
- nmdc-schema==11.6.1
+ nmdc-schema==11.7.0
```
...and then ran the following command (as usual):
```sh
$ docker compose run --rm --no-deps fastapi sh -c 'make update-deps'
```
Fixes #985 
I tested these changes by running `make test` locally and confirming the tests all pass.
```py
======= 140 passed, 5 skipped, 1 xfailed, 6 xpassed, 4 warnings in 66.09s (0:01:06) ========
```

Bump `nmdc-schema` to version `11.7.0` and synchronize transitive dependencies

---

docs/mkdocs.yml

On this branch, I fixed a bug I introduced earlier today via #991. In that PR, I moved the documentation source files, but I neglected to update this `edit_uri_template` configuration parameter accordingly. As a result, the "Edit on GitHub" links on the website did not work anymore. This PR fixes that by adding the missing path segment.
See summary.
Fixes #992 
I tested these changes by spinning up the documentation locally and confirming the "Edit on GitHub" links work.

Fix issue preventing "Edit on GitHub" links from working

---

nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/repair/database_updater.py
nmdc_runtime/site/repository.py
tests/test_data/test_database_updater.py

This PR adds a job called `generate_update_script_for_insdc_biosample_identifiers` which is visible/accessible through the Dagster/dagit interface with the same name (see attached screenshot).
You can run this job if you want to create a `/queries:run` compatible script that pulls in the information on the `ncbiBioSampleAccession` and `ncbiBioProjectAccession` fields from the GOLD API and asserts them on the `insdc_biosample_identifiers` and `insdc_bioproject_identifiers` slots.
Fixes https://github.com/microbiomedata/issues/issues/1174
...

Add a job that pulls in `insdc_biosample_identifiers` and `insdc_bioproject_identifiers` onto biosamples

---

.env.example
docker-compose.test.yml
docker-compose.yml

On this branch, I added to `.env.example` and used variable substitution in `docker-compose*.yml` files.
Closes #987
local dev setup.
I tested these changes by `make test`.
No doc updates strictly needed, as `dev`-stack defaults remain as is.

Customize host port mapping via `.env` file

---

nmdc_runtime/site/export/ncbi_xml.py
nmdc_runtime/site/export/ncbi_xml_utils.py
nmdc_runtime/site/resources.py
tests/test_data/test_ncbi_xml.py

NCBI XML export pipeline should restrict processing to only non-JGI samples

---

nmdc_runtime/api/endpoints/queries.py

On this branch, I updated an example request payload shown on Swagger UI for the `/queries:run` API endpoint, so that it is correct. On `main`, it is currently incorrect (it is missing the `"multi": true` property).
I also added a second example "update" command. Now, one example illustrates the updating of a single matching document, and another one illustrates the updating of all matching documents.
Fixes #1015 
I did not test these changes. I made the changes using GitHub's `github.dev` editor.

Fix incorrect `/queries:run` "update" command example (Swagger UI)

---

db/migrations/notebooks/migrate_11_7_0_to_11_8_0.ipynb

On this branch, I created a Python notebook that runs the schema `11.7.0`-to-`11.8.0` migrator.
~Note that a version of `nmdc-schema` that includes that migrator, has not been published to PyPI yet (i.e. https://github.com/microbiomedata/nmdc-schema/issues/2487 is still open). Until that has happened, the notebook–as it's currently written—will not work (it will fail to install the necessary Python package).~
N/A
Fixes #1016 
I have not tested these changes yet. I will test them once a version of `nmdc-schema` that includes the relevant migrator, has been published to PyPI.

Create Python notebook that runs schema `11.7.0`-to-`11.8.0` migrator

---

.env.example
nmdc_runtime/config.py

On this branch, I made it so the `IS_RELATED_IDS_ENDPOINT_ENABLED` config variable derives its value from an environment variable.
This is based upon a conversation that took place during today's referential integrity squad meeting.
Fixes #1045
Configuration.
I tested these changes by setting the environment variable via my local `.env` file, running `$ docker compose down fastapi && docker compose up fastapi --detach`, and confirming the Swagger UI showed what I expected. The actual feature flag functionality did not change in this PR—only how the flag gets raised/lowered.

Source the feature flag value from an environment variable

---

nmdc_runtime/api/endpoints/find.py

See https://github.com/microbiomedata/nmdc-runtime/issues/1049#issuecomment-3050436424
...

Changes to `/data_objects/study/{study_id}` because of change to `_type_and_ancestors` key in `alldocs`

---

requirements/main.in
requirements/main.txt

On this branch, I updated the `refscan` package to its latest version.
Refscan version `0.3.2` includes a bugfix for a bug that is blocking progress on https://github.com/microbiomedata/nmdc-runtime/pull/1065.
Fixes #1073
I tested these changes by confirming all tests pass locally.

Bump `refscan` version from `0.3.0` to `0.3.2`

---

db/migrations/notebooks/migrate_11_8_0_to_11_9_1.ipynb
nmdc_runtime/api/endpoints/find.py
nmdc_runtime/site/ops.py
requirements/main.in
requirements/main.txt
tests/files/planned_processes.json
tests/lib/faker.py
tests/test_api/test_endpoints.py
tests/test_ops/test_materialize_alldocs.py

On this branch, I bumped the schema version to ~11.9.0~ [11.9.1](https://github.com/microbiomedata/nmdc-schema/releases/tag/v11.9.1), ran the test suite, and addressed all test failures. I also implemented the associated migration notebook.
🚫 Please **review and approve**, but **do not merge**. @eecavanna wants to coordinate the merge with the running of a migrator (in the development environment).
There are other references to scalar (i.e. non-list) `was_informed_by` values in the repository, but I think they are all in stale code/examples, which would be cleaned up as part of https://github.com/microbiomedata/nmdc-runtime/issues/1028 (most of them are in the `metadata-translation` directory).
Fixes #1080 
I tested these changes by confirming all tests pass on GHA (and locally).
Also, …

Bump `nmdc-schema` version from `11.8.0` to `11.9.1`

---

db/migrations/ad_hoc_scripts/migrate_jobs_collection_from_schema_11.8.0_to_11.9.1.mongosh.js

On this branch, I replaced `use nmdc` (which works in Studio 3T, but not MongoDB Compass) with `use("nmdc")` (which works in MongoDB Compass, but not Studio 3T).
None.
Related to #1085
I tested these changes by running the changed command in Studio 3T (where it doesn't work) and MongoDB Compass (where it works).

Use MongoDB Compass syntax instead of Studio 3T syntax

---

nmdc_runtime/site/graphs.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/repair/database_updater.py
nmdc_runtime/site/repository.py
nmdc_runtime/site/resources.py
nmdc_runtime/site/translation/gold_translator.py
tests/test_data/test_gold_translator.py
tests/test_ops/test_gold_api_ops.py

This PR adds an option called `enable_biosample_filtering` to the GOLD translator and also to the database updater methods.
The `enable_biosample_filtering` option if set to `true` (default) will filter biosamples according to the current logic implemented for checking "validity" of sequencing project and then filtering out associated biosamples. However, if we disable the `enable_biosample_filtering` option (set to `false`) then we lose "valid biosample" filtering, and instead pull in all biosamples. We have also allowed for these options to be propagated through to the database stitcher jobs.
Addition of this logic was necessary for issue https://github.com/microbiomedata/issues/issues/1277 because we are trying to pull in all remaining biosamples (which got filtered out in the previous …

Add option to enable/disable filtering on biosamples in GOLD translator

---

nmdc_runtime/site/ops.py

In the https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/site/ops.py file, there is a [log message](https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/site/ops.py#L1643-L1645) (printed to the Dagster/Dagit console when the op is run) and when run on a study in its current state using dagit-dev, we run into the following error:
```
The above exception was caused by the following exception:
AttributeError: 'list' object has no attribute 'get'
File "/usr/local/lib/python3.10/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
yield
File "/usr/local/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
next_output = next(iterator)
File …
```

Update log message in `run_script_to_update_insdc_biosample_identifiers()` Dagster `@op`

---

nmdc_runtime/site/ops.py

The output type of the `run_script_to_update_insdc_biosample_identifiers()` op needs to be fixed b/c we know that it can return both a dict, as well as a list of dicts now.
...
...

fix output type of `run_script_to_update_insdc_biosample_identifiers()`

---

nmdc_runtime/api/endpoints/nmdcschema.py

Add query-param metadata and docstring to `/nmdcschema/linked_instances`

---

nmdc_runtime/api/db/mongo.py
nmdc_runtime/api/endpoints/nmdcschema.py
nmdc_runtime/api/main.py
nmdc_runtime/api/models/nmdc_schema.py
nmdc_runtime/config.py
nmdc_runtime/site/ops.py
nmdc_runtime/site/util.py
nmdc_runtime/util.py

On this branch, I replaced code that had been copied from the `refscan` repository with invocations of functions exposed by the `refscan` package, which is (i.e. was eventually made into) a dependency of `nmdc-runtime`.
I also removed a few unused `import` statements I noticed in the files that I otherwise made changes to.
Fixes #1005
I tested these changes by confirming that the tests run by `make test` all pass.

Replace copied `refscan` code with invocations of `import`-ed functions

---

db/migrations/notebooks/migrate_11_9_1_to_11_10_0.ipynb
requirements/dev.txt
requirements/main.in
requirements/main.txt

On this branch, I upgraded `nmdc-schema` to version 11.10.0.
N/A
https://github.com/microbiomedata/nmdc-runtime/issues/1132
I tested these changes by running automated test suite
N/A

Upgrade nmdc-schema to 11.10.0

---

.env.example
README.md
nmdc_runtime/api/main.py
nmdc_runtime/api/middleware.py
nmdc_runtime/config.py
requirements/main.in
requirements/main.txt

On this branch, I installed the `pyinstrument` package as a dependency, and documented how people can use it to see how much time "the computer" is spending executing various functions while servicing a given HTTP request.
I added a step-by-step guide to the `README.md`. The gist is that, when the feature is enabled (via an environment variable—disabled by default), when the user adds `?profile=true` to the URL in the address bar, the FastAPI app will process the request as normal, BUT will return an HTML-formatted performance report instead of the normal response payload.
Here's (on left) a screenshot of an example report (copied from the [Pyinstrument docs](https://pyinstrument.readthedocs.io/en/latest/home.html)):
> Note: In the official Pyinstrument …

Install and document usage of Pyinstrument for performance profiling

---

nmdc_runtime/api/main.py

On this branch, I did two main things:
1. I fixed the `/favicon.ico` endpoint, which was previously programmed to return a file at a path that did not lead to that file (causing the API to return an HTTP 500 response).
2. I hid the `/` (root) and `/favicon.ico` endpoints from Swagger UI (which resolves https://github.com/microbiomedata/nmdc-runtime/issues/1138).
I also added some documentation about the mounting of the `/static` directory.
Fixes #1153 
Fixes #1138
I tested these changes by visiting an arbitrary Runtime URL (except `/docs`) and confirming the favicon endpoint began working once I made this change.
| Before | After |
| --- | --- |
|  <img width="400" alt="image" src="https://github.com/user-attachments/assets/1eab54b2-77a3-4e29-a06e-347c4af1af1f" /> |  <img width="400" …

Fix `/favicon.ico` access and hide `/` and `/favicon.ico` endpoints from Swagger UI

---

README.md

On this branch, I refined the performance profiling instructions in the `README.md` to reflect things I learned since I wrote the initial version of the instructions (a few days ago).
N/A.
Fixes #1161 
Developer docs.
I tested these changes by following the instructions.

Refine performance profiling instructions

---

docs/content/nb/ontology_loader.ipynb

On this branch, I restored a JSON property that I had accidentally deleted via PR #1185 (oops).
I used VS Code's notebook viewer to automatically generate the property. It also automatically generated an additional, innocuous one.
Fixes #1194 
I confirmed MkDocs could process the updated notebook (and successfully build a documentation site).
```sh
uv run --active mkdocs build -f docs/mkdocs.yml
```
N/A

Fix issue in Jupyter notebook's own metadata (restore accidentally-removed JSON property)

---

nmdc_runtime/api/endpoints/find.py

On this branch, I deleted some unused code that raised an exception when the `templates` directory didn't exist. That directory was intentionally deleted as part of https://github.com/microbiomedata/nmdc-runtime/pull/1203.
I also deleted an adjacent snippet of unused code, although its presence wasn't causing any issues at run time.
I also deleted the unused imports in that file.
Fixes #1204 
I tested these changes by confirming all tests pass locally and on GHA.

Delete Jinja2 configuration statement that requires `templates/` directory to exist

---

nmdc_runtime/api/openapi.py

On this branch, I updated the description of a group of endpoints (the description appears on Swagger UI) so that, instead of implying that the endpoints retrieve information from the NMDC Data Portal, the description implies that the endpoints retrieve information from the NMDC database.
N/A
Fixes #1200 
Swagger UI.
I tested these changes by reading the sentence back to myself twice.

Update endpoint group description to not imply connection to Data Portal

---

nmdc_runtime/api/openapi.py

On this branch, I added a message to the top of the [Swagger UI](https://api.microbiomedata.org/) page, inviting users to contact us about their use cases.
Here's a screenshot of the message:
The "contact us" link (which opens in a new tab) points to the "Contact" page of the NMDC website:
```
https://microbiomedata.org/contact/
```
Fixes #945 
Swagger UI.
I tested these changes by confirming the message looks the way I expect and that, when I click on the "contact us" link, the "Contact" page of the NMDC website appears in a new web browser tab.

Add message to Swagger UI, inviting users to contact us about their use cases

---

docs/content/admin.md
pyproject.toml
tests/test_data/data/plant_air_jgi_input.yaml
tests/test_data/data/plant_air_jgi_output.yaml
uv.lock

On this branch, I updated the Runtime to use NMDC schema version 11.11.0 (instead of 11.10.0).
That involved doing two things:
1. Doing the usual `pyproject.toml` + `uv.lock` update
2. Fixing a test that was broken by the schema change
Fixes #1215 
Dependencies.
I tested these changes by ensuring `make test` passes locally and on GHA.

Bump `nmdc-schema` version to `v11.11.0` and update Runtime code
