microbiomedata/nmdc-runtime

- metadata-translation/src/bin/lib/nmdc_data_source.yaml
- metadata-translation/src/bin/lib/nmdc_dataframes.py
- metadata-translation/src/bin/lib/transform_nmdc_data.py
- nmdc_runtime/lib/nmdc_data_source.yaml
- nmdc_runtime/lib/nmdc_dataframes.py
- nmdc_runtime/lib/transform_nmdc_data.py
@dwinston @dehays  
I have made the necessary changes to include projects that don't have outputs. However, I am not confident in the counts.
In my gold dump, there are a total 889 projects. Of these:
- 168 have data objects as outputs.
- There are 123 projects in SPRUCE study
This leaves 598 projects in the exported data that do not have outputs and are not in the SPRUCE study. Do we still want to include those projects?
> Issue 35: add SPRUCE data

- Makefile
- requirements/main.txt
Can now `make update-schema` to only `--upgrade-package nmdc-schema` (rather than a broader `--upgrade`) when `pip-compile`ing deps to `requirements/main.txt`.
\cc @wdduncan @scanon @dehays
> feat: update-schema make target

- RELEASES.md
- components/workflow/workflow/core.py
- nmdc_runtime/api/boot/object_types.py
- nmdc_runtime/api/boot/triggers.py
- nmdc_runtime/api/main.py
- nmdc_runtime/api/v1/router.py
addded entries to api.boot.{object_types,triggers}. also reformatted files using black defaults.
examples used for dev:
- [readsqc-in-example.json](https://gist.github.com/dwinston/05a176b69744a3dfc52a1c8b07590867)
- [readsqc-in-example-drsobject.json](https://gist.github.com/dwinston/fac2cc17af2a281a06870981e0d7e63d)
> feat: readsqc-in trigger

- RELEASES.md
- nmdc_runtime/api/endpoints/util.py
- nmdc_runtime/api/v1/outputs.py
feat(api/jobs): return workflow
Instead of job specific data return the workflow record when a claim is made. Compute automation needs the workflow object returned to continue their happy path.
feat(releases): bump release
> feat(outputs): add client site authentication

- components/nmdc_runtime/workflow_execution_activity/core.py
- components/nmdc_runtime/workflow_execution_activity/spec.py
Create jobs for correct workflows
Rewrote the `create_jobs` function to only create new workflows if they do not have an activity already associated with them in the incoming workflow execution activity sets. This method creates a mapping of nodes and their children and then iterates through them to see if their children account for all of the workflow execution activities that should have been created already. If something is missing a new job will be created for it.
> Clean up job adding service for activities

- RELEASES.md
While reading `RELEASES.md`, I noticed the strings `Hub` and `1` were swapped from where I thought they belonged. I re-swapped them in this branch.
Source: https://github.com/microbiomedata/nmdc-runtime/blob/main/RELEASES.md
Source: https://github.com/microbiomedata/nmdc-runtime/blob/fix/fix-typo-in-RELEASES.md/RELEASES.md
> Fix typo in `RELEASES.md`

- docs/howto-guides/author-changesheets.md
Capture latest notes on how to update JSON document values that have substructure, i.e., lists, dicts, etc. using changesheets.
> update changesheets documentation

- nmdc_runtime/api/endpoints/util.py
- nmdc_runtime/api/models/util.py
also:
- bump page limit to 2k for `find` endpoints
- ensure no spurious cursor token for limit=0 of nmdcschema endpoints
closes #293
> feat: add projection to `find_` endpoints

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/resources.py
- requirements/dev.txt
- requirements/main.txt
Swagger interface for API docs aren't being built properly because newly added `requests-cache` library is not in the environment.
> update `dev.txt` and `main.txt` based on NEON soil ingest pipeline requirements

- README.md
I added a new step to the instructions in the README:
I also "filled in" some of the existing steps with a little more information.
> Add instructions for setting `mongoKeyFile` permissions

- docker-compose.test.yml
In this branch, I updated the Docker Compose file for the test stack, to use the `mongo` Docker image (instead of the Bitnami one), and to **not** configure the MongoDB server to run in replica set mode. This fixes an issue I ran into when running `$ make up-test`.
Closes #299
> Switch to `mongo` image without replica set, for test stack

- nmdc_runtime/api/endpoints/sites.py
- nmdc_runtime/minter/bootstrap.py
The interface to modifying the sites collection is limited to a single endpoint, so I think it is fine to directly call a function to perform the operation.
I can envision moving to a more event-driven handler architecture once enough of these cases are present. I don't think it's worth the added complexity at this time.
fixes #317
> fix: refresh minter.requesters collection on site creation

- components/nmdc_runtime/workflow_execution_activity/core.py
- nmdc_runtime/api/core/util.py
- nmdc_runtime/api/endpoints/objects.py
- nmdc_runtime/api/endpoints/operations.py
- nmdc_runtime/api/endpoints/queries.py
- nmdc_runtime/api/endpoints/runs.py
- nmdc_runtime/api/endpoints/search.py
- nmdc_runtime/api/endpoints/sites.py
- nmdc_runtime/api/endpoints/users.py
- nmdc_runtime/api/endpoints/util.py
- nmdc_runtime/api/main.py
- nmdc_runtime/api/models/run.py
- nmdc_runtime/core/exceptions/token.py
- nmdc_runtime/minter/adapters/repository.py
- nmdc_runtime/minter/entrypoints/fastapi_app.py
- nmdc_runtime/site/drsobjects/ingest.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/resources.py
- tests/files/nmdc_bsm-12-7mysck21.json
- tests/files/nmdc_sty-11-pzmd0x14.json
- tests/integration/test_minter_repository.py
- tests/test_api/test_endpoints.py
- tests/test_api/test_metadata.py
- util/mongorestore-nmdc.sh
add regression test
closes #345
replaces many instances of pydantic-model-to-dict calls (`.dict(...)`) with `.model_dump(mode="json",...)` calls as per pydantic V2 guidance.
> fix: ensure pydantic models serialize to json-compatible `dict`s.

- components/nmdc_runtime/workflow_execution_activity/core.py
- nmdc_runtime/api/endpoints/objects.py
- nmdc_runtime/api/endpoints/operations.py
- nmdc_runtime/api/endpoints/queries.py
- nmdc_runtime/api/endpoints/runs.py
- nmdc_runtime/api/endpoints/search.py
- nmdc_runtime/api/endpoints/sites.py
- nmdc_runtime/api/endpoints/users.py
- nmdc_runtime/api/endpoints/util.py
- nmdc_runtime/api/main.py
- nmdc_runtime/api/models/object.py
- nmdc_runtime/api/models/operation.py
- nmdc_runtime/api/models/run.py
- nmdc_runtime/minter/adapters/repository.py
- nmdc_runtime/minter/entrypoints/fastapi_app.py
- nmdc_runtime/site/drsobjects/ingest.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/resources.py
- tests/integration/test_minter_repository.py
- tests/test_api/test_endpoints.py
- tests/test_graphs/ensure_jobs.py
ensures `model_dump` preserves python `datetime`s, which are handled by pymongo.
reverts mode='json' option to model_dump, to preserve datetimes.
fixes #349
> fix: use @field_serializer for pydantic `Url`s

- RELEASES.md
- requirements/main.in
- requirements/main.txt
- I updated `main.in` and then ran `make update-deps` to update `main.txt` accordingly
- I updated the changelog
CC: @Shalsh23
> Update `nmdc-schema` package from `8.0.0` to `8.1.2`

- RELEASES.md
- requirements/main.in
- requirements/main.txt
There is no data migration associated with (or necessary for / written for) this schema change.
> Update `nmdc-schema` package from `9.0.4` to `9.1.0`

- nmdc_runtime/api/core/metadata.py
include mongo-command update_info writeErrors when determining HTTP response code
fixes #326
> fix: include mongo-command writeErrors for http response code

- nmdc_runtime/site/resources.py
> fix: coerce pydantic AnyUri to str when needed

- .github/workflows/build-and-release-to-spin.yml
Follow up to #382. 
Apparently variables cannot be define in terms of other variables in GitHub workflows. This changes the main release workflow so that all the variables are defined up top and shared with downstream jobs using [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files).
> Replace illegal variable defined using other variable

- .github/workflows/build-and-release-to-spin.yml
Follow up to #390.
I thought I understood the GitHub workflows environment file thing, but oops not quite. I think those values are only sent to the runners so they can't be used for things like `enable=${{ env.IS_PROD_RELEASE }}` outside of `run` in a `step`. So, back to using a workflow-level `env` block.
> Revert to using env context for variables

- .github/workflows/build-and-release-to-spin.yml
> Use local path context when running docker build so that it knows about git tags

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_data/test_submission_portal_translator.py
- tests/test_data/test_submission_portal_translator_data.yaml
Re: https://github.com/microbiomedata/submission-schema/issues/162
These changes are all around support for bringing data from a GLBRC submission into Mongo. Summary of changes:
* In the latest version of the schema `dataset_dois` has been replaced by `associated_dois` on the `Study` class. The range of `associated_dois` is a `Doi` class which has two required slots and one conditionally required slot. These changes update the `SubmissionPortalTranslator` to adhere to that. However since the submission portal does not yet collect some of the newly required information, it is being piped in via Dagster `op` inputs instead. So, _for now_ the person running this pipeline will be responsible for filling in these values. 
* Similarly, `study_category` is now required on the `Study` class, but …
> Updates to submission portal-to-Mongo pipeline to support GLBRC data

- README.md
- I added the PyPI and DockerHub URLs to the README
I find it difficult to remember those URLs. In the case of the DockerHub ones, I also find it difficult to find them via Google.
One downside to documenting them statically like this is that clones of this repository will still have the same links. I think that is a common compromise people make when documenting links to deployments in READMEs. It is one I'm comfortable making.
> Add PyPI and DockerHub links to `README.md`

- nmdc_runtime/api/endpoints/objects.py
> ensure no w3id.org loop; use data portal API

- nmdc_runtime/api/endpoints/metadata.py
- nmdc_runtime/api/endpoints/queries.py
- I updated two HTTP responses so they no longer contain lists of usernames, which people could use to learn about API user accounts
Fixes https://github.com/microbiomedata/nmdc-runtime/issues/399
> Remove username lists from error messages in HTTP responses

- nmdc_runtime/site/translation/gold_translator.py
- tests/test_data/test_gold_translator.py
As a result of the discussion on https://github.com/microbiomedata/issues/issues/527 a couple of trivial edits needed to be made to the GOLD-to-Mongo ingest pipeline:
* Use lowercase `gold` while making CURIEs for GOLD entities
* Modification to the logic in `_get_quantity_value()` to accommodate special handling of _depth_ data
> NMDC depth.has_minimum_numeric_value — GOLD depthInMeters
> NMDC depth.has_maximum_numeric_value — GOLD depthInMeters2
> depthInMeters2 may or may not be present in GOLD, so in the cases where it’s not provided:
> NMDC depth.has_numeric_value — GOLD depthInMeters
> Misc. updates to `gold_translator.py`

- nmdc_runtime/api/endpoints/queries.py
- nmdc_runtime/api/models/query.py
closes #356
- sends a 200
- updates the document
- Throws an error if no records found
- Throws an error if query is poorly formatted
> allow mongodb update command via POST /query:run

- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_data/test_submission_portal_translator.py
- tests/test_data/test_submission_portal_translator_data.yaml
This is part 2 of https://github.com/microbiomedata/issues/issues/543.
The changes here update the `SubmissionPortalTranslator` class so so that when it is creating `Biosample` instances, the `env_package` slot is populated by default from the submission-level `packageName` field. Tests updated accordingly.
> Allow Biosample.env_package to be populated from submission-level data

- nmdc_runtime/api/main.py
closes #325
note: I just built an index on each of dev and prod, so deploying this involves no risk of failure to startup due to failure of index creation.
> fix: unique index on username for users collection

- .gitpod.yml
- Makefile
I didn't think I should change anything beside `Makefile` and `.gitpod.yml`. In fact I'm not even sure about `.gitpod.yml`.
There were many appearances of `docker-compose` in files from the dependencies, and also in the context of the `docker-compose.yml` filename
> Replace `docker-compose` with `docker compose`

- demo/metadata_migration/notebooks/migrate_9_3_2_to_10_0_0.ipynb
- Updated a statement that incorrectly said the origin server was typically local (not true) and the transformer server is typically remote (not true); to say the opposite.
> Fix inaccurate comment in migration instructions

- .github/workflows/python-app.yml
- docker-compose.test.yml
- nmdc_runtime/test.Dockerfile
- tests/e2e/test_minter_api.py
- tests/integration/test_minter_repository.py
- tests/test_api/test_endpoints.py
- tests/test_data/test_gold_translator.py
- tests/test_data/test_neon_benthic_data_translator.py
- tests/test_data/test_neon_soil_data_translator.py
- tests/test_graphs/test_submission_portal_graphs.py
- tests/test_util.py
This PR skips all currently failing tests in order to restore the github action that runs automated tests for each PR
Related to: https://github.com/microbiomedata/nmdc-runtime/issues/301
> 301-part-1-skip-pytest-failures

- nmdc_runtime/api/endpoints/workflows.py
- nmdc_runtime/api/v1/workflows/activities.py
- tests/test_api/test_endpoints.py
Fixes #478
> - fixes bug in `v1/workflows/activities` endpoint documented in #478   
> - NOTE: this v1 endpoint will be removed in a future PR
> - introduces NEW `workflows/activities` endpoint that duplicates the functionality of the above 
> - [x] Add "Deprecated" note to v1
> - [x] Add workflows/activities documentation
Used example in #478 for added `test_submit_workflow_activities` test.
> 478 refactor v1 workflows activities endpoint

- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
Upping nmdc-scheam from 10.0.0 to 10.1.0 to add new file type enums for binning.
> Bump `nmdc-schema` from `10.0.0` to `10.1.0`

- requirements/main.in
- requirements/main.txt
This upgrades the `nmdc-schema` dependency from 10.1.0 to 10.1.2. There _shouldn't_ be substantive schema changes between the two, except that both 10.1.0 and 10.1.1 were incorrectly built before release.
@aclum expressed interest in making an off-cycle release of `nmdc-runtime` once this change has been deployed to and tested (by workflows) on dev.
> Upgrade to nmdc-schema 10.1.2

- demo/metadata_migration/notebooks/migrate_A_B_C_to_X_Y_Z.ipynb
In PR https://github.com/microbiomedata/nmdc-runtime/pull/487, I committed a Jupyter notebook that I didn't know was not formatted in a valid way.
In this PR, I am committing the same notebook in a valid way.
The invalid one was saved using PyCharm and the valid one was saved using VS Code. The PyCharm GUI has been buggy when it comes to Python notebooks, and—based on this issue—I think the under-the-hood piece of PyCharm that deals with Python notebook is buggy, too. I'm going to switch back to using VS Code for notebooks for now.
Fixes #490 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration, if it is not simply `make …
> Migrations: Fix invalid example notebook

- nmdc_runtime/api/endpoints/workflows.py
- nmdc_runtime/api/v1/workflows/activities.py
Documents other than activities may be generated and submittable at the same time.
closes #462
> fix(validation): allow any valid nmdc:Database to [/v1]/workflows/activities

- docs/howto-guides/author-changesheets.md
Updates docs for changesheet validator to include `remove` action
Fixes #498 
Please delete options that are not relevant
Successfully submitted a changesheet through API endpoint using this action
> update docs for changesheet validator to include `remove` action

- .env.example
- nmdc_runtime/api/main.py
Supplement to microbiomedata/nmdc-server#1211
Fixes #507
**Configuration Details**: new env var `INFO_BANNER_INNERHTML`.
> load optional info banner via env var

- nmdc_runtime/api/analytics.py
The changes on this branch make it so the analytics middleware no longer raises a `KeyError` when the incoming request lacks a `user-agent` (case-insensitive) header.
If someone wants the runtime to deny those requests, I propose that be done elsewhere (and explicitly documented).
Fixes #515.
I confirmed, locally (shown [here](https://github.com/microbiomedata/nmdc-runtime/pull/516#issuecomment-2096659783)), that requests that lack a `User-Agent` header are now logged by the analytics middleware. I also confirmed that requests that _have_ the header are also logged (as they were before).
> Update analytics middleware to log requests lacking a `user-agent` header

- nmdc_runtime/api/main.py
In this branch, I made it so the Runtime will respond to requests originating from `https://microbiomedata.github.io` (i.e. web clients hosted on GitHub Pages). That will enable team members to develop unofficial web clients that can streamline certain processes while similar functionality does not exist in the Runtime (maybe by design).
Fixes #508
It has not been tested beyond observing that none of the GitHub Actions workflows fail with the change present.
- GitHub Actions ran it for me
> Configure CORS to allow requests from clients hosted on GitHub Pages

- nmdc_runtime/api/endpoints/nmdcschema.py
- tests/test_api/test_endpoints.py
In this branch, I implemented a new API endpoint. Its behavior is described in its docstring, shown here:
```py
@router.get("/nmdcschema/ids/{doc_id}/collection-name")
def get_collection_name_by_doc_id(
doc_id: str,
mdb: MongoDatabase = Depends(get_mongo_db),
):
r"""
Returns the name of the collection, if any, containing the document having the specified `id`.
This endpoint uses the NMDC Schema to determine the schema class of which an instance could have
the specified value as its `id`; and then uses the NMDC Schema to determine the names of the
`Database` slots (i.e. Mongo collection names) that could contain instances of that schema class.
This endpoint then searches those Mongo collections for a document having that `id`.
If it finds one, it responds with the name of the collection …
```
> Implement API endpoint that returns name of collection containing document having a given `id`

- demo/metadata_migration/notebooks/migrate_10_3_0_to_10_4_0.ipynb
In this branch, I created a Python notebook that can be used to migrate a Mongo database from conforming to schema v10.3.0 to conforming to schema version v10.4.0. That migrator was introduced into the `nmdc-schema` repo "late" (i.e. in v10.5.4).
Fixes #556 
Ran locally and validated the migrated result.
> Implement migration notebook for `v10.3.0` to `v10.4.0`

- demo/metadata_migration/notebooks/requirements.txt
In this branch, I committed code I meant to commit in PR branch https://github.com/microbiomedata/nmdc-runtime/pull/558. A full explanation is in the description of issue https://github.com/microbiomedata/nmdc-runtime/issues/561.
As a reminder, this `requirements.txt` file is only used by the migration notebooks and has no impact on the Runtime.
> Bump migration notebooks' `pymongo` dependency to accommodate `nmdc-schema`

- .github/workflows/build-and-release-to-spin.yml
In this branch, I updated a GitHub Actions workflow so that, when it builds a container image and pushes it to Docker Hub, it also pushes a copy to GitHub Container Registry. That will make `nmdc-runtime` work more similarly to other NMDC products/applications (i.e. `nmdc-server`, `nmdc-edge`, and `nmdc-aggregator`).
Fixes #564 
It has not been tested yet. The final test will be whether Runtime package(s) appear at https://github.com/orgs/microbiomedata/packages once this new GHA workflow runs.
> Configure GitHub Actions to push container image to GitHub Container Registry (in addition to Docker Hub)

- .github/workflows/build-and-release-to-spin.yml
This is an attempt to fix the HTTP 403 Forbidden error that occurred in this [GHA workflow run](https://github.com/microbiomedata/nmdc-runtime/actions/runs/9587845790/job/26438682126), which was triggered by the merging of PR https://github.com/microbiomedata/nmdc-runtime/pull/565.
```fortran
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/microbiomedata/nmdc-runtime-fastapi:main: failed commit on ref "manifest-sha256:***": unexpected status from PUT request to https://ghcr.io/v2/microbiomedata/nmdc-runtime-fastapi/manifests/sha256:***: 403 Forbidden
```
In this branch, I configured the GHA workflow step to authenticate with GHCR as the user triggering the workflow instead of as the repository owner. This makes it consistent with how it is done in …
> Authenticate as workflow triggerer instead of as repo owner

- Makefile
- nmdc_runtime/util.py
- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
In this branch, I bumped `nmdc-schema` from `10.3.0` to `10.5.4` in `requirements/main.in`, then I ran `$ make update-deps` to synchronize the other requirements files.
> Bump `nmdc-schema` from `10.3.0` to `10.5.5`

- nmdc_runtime/site/repository.py
- nmdc_runtime/site/resources.py
- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_api/test_endpoints.py
- tests/test_data/test_submission_portal_translator_data.yaml
- tests/test_graphs/test_submission_portal_graphs.py
- tests/test_ops/test_data_api_ops.py
The Portal API has replaced session cookie-based authentication with Bearer token authentication. These changes update `NmdcPortalApiClient` to reflect that.
In testing I also found that the `SubmissionPortalTranslator` has drifted away from the Portal a bit. In particular, `samp_name` is now the unique key slot on `Biosample` instances instead of `source_mat_id`. These changes also correct that.
Fixes #571 
- These changes update `tests/test_ops/test_data_api_ops.py` to reflect the new behavior of `NmdcPortalApiClient`.
- These changes fix the test configuration of `tests/test_graphs/test_submission_portal_graphs.py` and remove the `xfail` mark.
> Update `NmdcPortalApiClient` with new authentication scheme

- demo/metadata_migration/notebooks/migrate_10_3_0_to_10_4_0.ipynb
Note: I erased the usual PR boilerplate content from this PR.
In this branch, I updated a migration notebook to use a newer version of the `nmdc-schema` PyPI package. Using a newer version was necessary in order to get access to a recently-revised migrator.
The revised migrator uses an additional collection, so I added that to the notebook.
Also, I fixed the format string for the logger (while I was already editing the notebook).
> Update notebook to use revised migrator (via newer `nmdc-schema` PyPI package)

- nmdc_runtime/site/translation/gold_translator.py
- nmdc_runtime/site/translation/neon_benthic_translator.py
- nmdc_runtime/site/translation/neon_soil_translator.py
- nmdc_runtime/site/translation/neon_surface_water_translator.py
- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
In this branch, I made it so the Runtime depends upon the "Berkeley schema" instead of the "legacy schema." That made it so the Runtime could no longer boot; so, in this branch, I also addressed the issue preventing it from booting, which was that some modules were referencing `nmdc.OmicsProcessing`, which no longer exists.
Fixes #578
I _assume_ this is a breaking change. Determining whether — and the extent to which — it is a breaking change is out of scope of this PR. This is a PR that will kick off multiple follow-up PRs.
Fixing failing tests is out of scope of this PR. This is a PR that will kick off multiple follow-up PRs.
> Switch to "Berkeley schema" and eliminate broken references preventing application startup

- .github/workflows/build-and-release-to-spin-berkeley.yml
In this branch, I added a GHA workflow that builds a container image from the `berkeley` branch, pushes that container image up to GHCR, and then redeploys the Runtime/Dagster workloads in the `nmdc-berkeley` namespace on Spin.
I expect this workflow to be a **temporary** one that will be deleted in several months, once the Berkeley Schema Roll Out squad ends and the `nmdc-berkeley` namespace on Spin gets deleted.
Fixes #582 
- This has not been tested yet. Once it has been merged into `main`, I will test it by making a change on the `berkeley` branch and verifying that the workflow runs, container images get pushed to GHCR, and Spin workloads get redeployed.
> Add GHA workflow that deploys app to `nmdc-berkeley` Spin namespace

- nmdc_runtime/minter/config.py
In this branch, I updated the minter so that, in addition to extracting typecodes verbatim from patterns in the schema, it now also extracts the first typecode in a `(...|...|...)`-formatted sequence.
I also added a `TODO` comment about moving away from extracting typecodes from these pattern strings, which I think are authored with the mindset of "here's what I want the schema to allow for values in this field," as opposed to "here's what I want the minter to use when creating an ID."
Fixes https://github.com/microbiomedata/nmdc-runtime/issues/592
> No, I'll leave that to the GitHub Actions workflow once I open the PR
> Update minter to use first typecode when pattern contains multiple typecodes

- nmdc_runtime/api/endpoints/sites.py
> doc: clarify that user must be site admin to generate site credentials

- nmdc_runtime/api/core/metadata.py
- tests/files/test_changesheet_update_bytes_ranged_slot.tsv
- tests/test_api/test_metadata.py
Infer python builtin type for coercion via <https://w3id.org/linkml/base>.
Fixes #613
> fix: changesheet can update bytes-ranged slot

- nmdc_runtime/site/export/ncbi_xml.py
- nmdc_runtime/site/export/ncbi_xml_utils.py
- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- tests/test_data/test_ncbi_xml.py
> Add broker name to NCBI XML, and also pull in `protocol_link.name` from LibraryPreparation objects

- nmdc_runtime/api/db/mongo.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/util.py
- tests/test_api/test_endpoints.py
- tests/test_ops/test_hello.py
- tests/test_ops/test_ops.py
Just like not all heroes wear capes, not all not all schema collections suffix with `_set`s.
Interpret `perform_mongo_updates` for non-`id`-having schema collections as simple insertions. Leave note in code about decision to insist on schema-supplied uniqueness signal.
This is a hack because e.g. <https://w3id.org/nmdc/FunctionalAnnotationAggMember> documents appear by eye to be unique via a compound key (metagenome_annotation_id, gene_function_id) and yet this is not explicit in the schema.
One potential solution is to auto-generate an `id` for such documents as a deterministic hash of the compound key, but any such `id` generation strategy should be unambiguous to a schema consumer such as nmdc-runtime.
For now, decision is to potentially re-insert "duplicate" documents, i.e. to …
> not all schema collections suffix with `_set`s

- nmdc_runtime/site/ops.py
for #631
Tested my manual trigger of `apply_metadata_in` job. Not closing #631 -- left `TODO` to add test coverage, but will merge now to ensure fix is active asap.
> hotfix: op fails due to invalid helper method invocation

- .env.example
- nmdc_runtime/api/core/auth.py
- nmdc_runtime/api/endpoints/users.py
- nmdc_runtime/api/main.py
In this branch, I made it so that the Runtime can be configured to use either the sandbox ORCID environment or the production ORCID environment, via an environment variable. If the environment variable is not defined, the Runtime will default to using the production ORCID environment.
Note: The base branch of this PR is the `berkeley` branch, not the `main` branch.
Fixes #636 
- I have not tested this outside of GitHub Actions. I will rely on a GitHub Actions workflow to test it.
> Get ORCID base URL (production vs. sandbox) from environment variable

- nmdc_runtime/api/core/auth.py
In this branch, I made it so, if the app is configured to use the sandbox ORCID environment, then the app will _also_ use the sandbox JWKS descriptor (instead of always using the production JWKS descriptor).
FYI: Here's a document containing a description of each JWKS property: https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-key-set-properties
Fixes #638 
- I haven't tested this. I will wait for the GitHub Actions workflow to run its tests and confirm that they are "in no worse shape" than on the `berkeley` branch.
> Use ORCID environment-specific JWKS values and clean up existing comments

- nmdc_runtime/site/translation/neon_benthic_translator.py
- nmdc_runtime/site/translation/neon_soil_translator.py
- tests/test_data/test_neon_benthic_data_translator.py
- tests/test_data/test_neon_soil_data_translator.py
This PR fixes test for neon translator code which will allow us the move the pytest xfail.
Fixes #470
using gitlab action tests
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the definition of done is intended …
> 470 missing attribute qualitycontrolreport causing multiple neon tests to fail

- tests/test_api/test_endpoints.py
Here are the changes I made in this PR branch:
1. **I removed the test set up code** that downloaded and restored a static Mongo dump that conformed to a specific version of `nmdc-schema`.
1. That code was not compatible with branches of the Runtime on which a different version of `nmdc-schema` was in use. In practice, we saw test failures when the Runtime was using the "Berkeley schema" (i.e. `nmdc-schema` version 11.x); but I think we would have seen test failures even when the Runtime was using certain versions of the legacy schema (i.e. `nmdc-schema` version 10.x), depending upon how that schema version differed from the one the dump happens to conform to.
2. **I removed the test** that depended upon the aforementioned (removed) set up code loading specific data into the `alldocs` …
> Remove test code's dependence on a static Mongo dump

- nmdc_runtime/api/main.py
In this branch, I updated Swagger tag descriptions to be consistent with the latest Berkeley Schema-compatible API GUI how-to guide ([here](https://github.com/microbiomedata/NMDC_documentation/blob/7f0ce6d7f671785e4733fdc14eac0c2f766b6cb9/docs/howto_guides/api_gui.md)). That was my main objective.
While I was at it, I also disabled a buggy feature, where expanding a table within a tag description would simultaneously collapse the endpoints in that tag section; and vice versa. This was happening because the click event was being propagated up the DOM tree, being received be listeners at every level (i.e. there was no `event.stopPropagation()` happening within the tag description level). Now, the table is always visible.
Fixes #646 
Please …
> Update Swagger tag descriptions to match Berkeley API GUI how-to guide

- nmdc_runtime/api/main.py
- Restored hyperlinks to the freeform blurb in the "Metadata" section of Swagger UI
- Removed the word "activities" from the overall Runtime description that appears at the top of Swagger UI
- Removed a broken image reference
- Changed some links to use `w3id.org` URL instead of schema docs URL
Fixes #685
> Restore hyperlinks to "Metadata" section and modernize Runtime description

- tests/test_api/test_endpoints.py
This PR fixes test_submit_workflow_activities to be compatible with berkeley schema
Fixes # [(issue)](https://github.com/microbiomedata/nmdc-runtime/issues/683)
testing is from github acations
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be …
> `berkeley`: Unskip `test_submit_workflow_activities` test and make it work with Berkeley schema

- tests/test_data/test_neon_benthic_data_translator.py
- tests/test_data/test_neon_soil_data_translator.py
- tests/test_ops/test_gold_api_ops.py
In PR https://github.com/microbiomedata/nmdc-runtime/pull/676, I configured pytest to skip running the following tests:
1. All tests in: `tests/test_data/test_neon_benthic_data_translator.py`
2. All tests in: `tests/test_data/test_neon_soil_data_translator.py`
3. All (4) tests in: `tests/test_ops/test_gold_api_ops.py`
In this PR, I have undone that; i.e. I've unskipped them, so that pytest will run them.
Fixes #687
- 👀 
> `berkeley`: Restore tests that were being skipped by mistake (oops)

- nmdc_runtime/site/ops.py
Fixed a bug in the code that was being used to generate the alldocs collection.
Options:
- See first commit (ea17ec3) for the not optimized algorithm that @PeopleMakeCulture, @sujaypatil96, and @eecavanna discussed in real time on Thursday.
- See second commit (1c5788d) for an optimized algorithm that @eecavanna thought of later and did not run by @PeopleMakeCulture or @sujaypatil96. Y'all can revert to the first commit if you want.
The bug in the original code was that a single document in each collection was being used to get the class ancestry of _every_ document in that collection. This could produce incorrect class ancestries when dealing with a database that conforms to the Berkeley schema, since a collection can store documents of differing types.
In the first commit, we changed it …
> `berkeley`: Determine class ancestry per-type value (within collection) instead of per-collection (when generating `alldocs`)

- .github/workflows/python-app.yml
In this branch, I configured the GitHub Actions (GHA) workflow that runs `pytest`, so that developers will be able to trigger (i.e. run) it manually (i.e. by clicking a button in the GitHub web GUI). Developers will be able to do that on _any_ branch of this repo; once this configuration exists in the `main` branch, specifically.
> [!IMPORTANT]  
> The base branch of this PR is frozen. I want to make an exception for this PR. It does not affect the behavior of the Runtime application in any way and it has no implications for things downstream of the Runtime. It only enables a new option within the "Actions" tab of this repository on GitHub.
> Configure `pytest` GHA workflow so developers can trigger it manually

- nmdc_runtime/site/ops.py
In this branch, I fixed a bug in the function that generates the `alldocs` collection. The bug was causing the `alldocs` collection to lack one document from each upstream collection.
This fixes the `E` failures that pytest recently began reporting on the `berkeley` branch (their absence is shown here).
> Fix bug where one document in each collection is omitted from `alldocs`

- demo/metadata_migration/notebooks/migrate_11_0_0_to_11_0_1.ipynb
- requirements/main.in
- requirements/main.txt
In this branch, I updated the `nmdc-schema` package to `11.0.1` and synchronized transitive dependencies. I also added a "no op" migration notebook for the jump from 11.0.0 to 11.0.1.
Fixes #720
> Update `nmdc-schema` package to `11.0.1` and synchronize transitive dependencies

- nmdc_runtime/site/export/ncbi_xml.py
- nmdc_runtime/site/export/ncbi_xml_utils.py
- nmdc_runtime/site/export/study_metadata.py
- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- tests/test_data/test_ncbi_xml.py
This PR "migrates" the NCBI XML Export pipeline to be conformant with the newly released berkeley schema (nmdc-schema==v11.0.0). It also updates the corresponding tests.
Fixes #721 #630 
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to each feature since the …
> NCBI XML Export pipeline migration

- nmdc_runtime/site/translation/gold_translator.py
Fix to remove missed `part_of` that was still being asserted on `NucleotideSequencing`. Not sure how I missed/overlooked this when working on the "migration" of this translator to make it conformant with the berkeley schema.
This is a priority hotfix we need to get merged in tomorrow, 10/11.
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the …
> Remove `part_of` still being asserted on `NucleotideSequencing`

- mkdocs.yml
The index page on our web docs currently doesn't show the documentation pages made for translators and exporters in PR #729 
Merge this PR for them to be made visible/accessible through the index page.
> Web docs index page missing translators/exporter tutorials

- nmdc_runtime/api/endpoints/queries.py
This PR updates the examples for queries:run to use valid nmdc identifiers and replaces part_of with associated_studies to be compliant with the berkeley schema rollout.
Fixes #734 
A simple checklist of necessary activities that add verifiable/demonstrable value to the product by asserting the quality of a feature, not the functionality of that feature; the latter should be stated as acceptance criteria in the issue this PR closes. Not all activities in the PR template will be applicable to …
> Update queries:run examples

- nmdc_runtime/api/core/auth.py
Extends the default access token expiration time to 1 day
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
- `make up-dev` and test ORCID login via local Swagger UI
- may need to update the `ORCID_NMDC_CLIENT_ID` and `ORCID_NMDC_CLIENT_SECRET` in .env file (see: Rancher)
> Make default expiry 24 hours

- nmdc_runtime/api/endpoints/find.py
- nmdc_runtime/site/ops.py
This PR seeks to add logic to the [/data_objects/study/{study_id}](https://api-dev.microbiomedata.org/docs#/find/find_data_objects_for_study_data_objects_study__study_id__get) endpoint so it also takes into account data object records that are related to biosamples by way of a `was_informed_by` relationship as opposed to just `has_input`/`has_output`.
Fixes #723
> `/data_objects/study/{study_id}` should take into account `was_informed_by` relationships

- nmdc_runtime/api/endpoints/nmdcschema.py
In this branch, I added some documentation to an API endpoint that lacked it. The API endpoint was introduced via https://github.com/microbiomedata/nmdc-runtime/pull/386 (to resolve issue https://github.com/microbiomedata/nmdc-runtime/issues/385).
Fixes #747 
- I read it back to myself and it made sense to me
> Document the `/nmdcschema/typecodes` API endpoint (reverse engineered)

- demo/metadata_migration/notebooks/helpers.py
- demo/metadata_migration/notebooks/test_helpers.py
- nmdc_runtime/api/core/metadata.py
- tests/files/nmdc_bsm-11-0pyv7738.json
- tests/files/test_changesheet_decimal_value.tsv
- tests/test_api/test_metadata.py
Because "Decimal" is not a Python `builtins` type, and because (py)mongo does not natively json-encode decimal values, and furthermore because existing behavior assumes decimal values will be supplied as floats (as JSON does not support decimals), added case to coerce decimal-typed values to `float`, and left inline comment explaining decision and options for decimal support in future.
Fixes #613
> fix: check for LinkML base type "Decimal" on loading changesheet

- demo/metadata_migration/notebooks/.notebook.env.example
- demo/metadata_migration/notebooks/migrate_11_0_3_to_11_1_0.ipynb
In this branch, I created a new migration notebook. This one can be used to migrate the Mongo database from conforming to schema version `11.0.3` to conforming to schema version `11.1.0`.
There is a caveat, though: Since the new schema hasn't been released yet, I don't know what its version number will actually be. I have assumed it will be `11.1.0`, but that may not be what it ends up being—in which case, I'll update this branch.
I also moved some notes from the notebook to the example config file. Finally, I changed the `import` section so that the migrator gets imported based upon a string variable. That will make it easier for us to transition from using a notebook to using a regular Python script (we can pass the string in as a CLI argument).
Fixes #760 
I tested the notebook locally …
> Implement the `11.0.3`-to-`11.1.0` migration notebook

- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
- tests/test_ops/test_ops.py
In this branch, I bumped the `nmdc-schema` package dependency from version `11.0.3` to version `11.1.0` in preparation for next week's release.
I also (effectively) ran `$ make update-deps` to synchronize the transient dependencies with the above change.
Note: Technically, I ran the following, container-based command in an attempt to further decouple the process from my host machine:
```shell
docker compose run --rm -it --name nmdc-runtime-builder fastapi sh -c 'make update-deps'
```
Fixes #768 
The subsystem is: Dependencies
I'll leave that to GitHub Actions.
I am assuming there is no documentation in `nmdc-runtime` that will be any less accurate with respect to `11.1.0` than with respect to `11.0.3`.
> Bump `nmdc-schema` from `11.0.3` to `11.1.0` and sync transitive dependencies

- nmdc_runtime/site/translation/gold_translator.py
- nmdc_runtime/site/translation/submission_portal_translator.py
- nmdc_runtime/site/translation/translator.py
- tests/test_data/test_submission_portal_translator.py
- tests/test_data/test_submission_portal_translator_data.yaml
- tests/test_data/test_translator.py
These changes update the submission portal data translator to place the JGI proposal ID into the `jgi_portal_study_identifiers` slot on `Study`. Previously it was placing it in `alternative_identifiers`, which is all that was available when the translation code was originally written.
Additional minor changes:
* Previously the submission portal data translator was prepending the prefix `GOLD:` to GOLD study IDs. This has been updated to `gold:`.
* The `Translator._get_curie()` method has been renamed to `Translator._ensure_curie()`. The behavior and calling semantics have been changed a bit to clarify that it _will not_ add a prefix if the provided identifier already has one. See test cases in `tests/test_data/test_translator.py` for examples.
* …
> Fix handling of GOLD and JGI IDs in submission data translator

- nmdc_runtime/api/endpoints/queries.py
- tests/test_api/test_endpoints.py
In this branch, I updated `/queries:run` so that it performs equivalent validation to that of `/metadata/json:submit` for `update` queries.
Fixes #774
`test_queries_run_update` automated test.
> Ensure basic validation occurs for updates via `POST /queries:run`

- demo/metadata_migration/notebooks/bookkeeper.py
- nmdc_runtime/api/core/auth.py
Fix to address deprecated datetime.utcnow() calls
> Replace deprecated `utcnow()` calls with `now(timezone.utc)`

- .env.example
- Makefile
- util/get_latest_nmdc_prod_dump_dir.sh
In this branch, I update the `mongorestore-nmdc-db` `Makefile` target to not use streaming gzipping. I use `rsync` instead, which will also speed up re-runs. I Introduce the `MONGO_REMOTE_DUMP_DIR` environment variable, along with guidance in `.env.example` for updating it with the "latest" remote directory name (via a one-liner utility script `util/get_latest_nmdc_prod_dump_dir.sh`.
Closes #800
I tested these changes by running
```bash
make nersc-sshproxy # ensures ssh identity file `~/.ssh/nersc`
export NERSC_USERNAME=dwinston
export MONGO_REMOTE_DUMP_DIR=$(ssh -i ~/.ssh/nersc -q ${NERSC_USERNAME}@dtn01.nersc.gov 'bash -s ' < util/get_latest_nmdc_prod_dump_dir.sh 2>/dev/null)
make mongorestore-nmdc-db
```
Documentation is inline (rather than in `docs` directory), and it was updated …
> Simplify local mongorestore of remote mongodump

- nmdc_runtime/api/endpoints/nmdcschema.py
- nmdc_runtime/api/endpoints/util.py
In this branch, I updated documentation about an API endpoint and a helper function that it calls.
I updated user-facing documentation about an API endpoint in an attempt to help users avoid performance-related surprises and to more easily work around them if they do encounter them. This documentation gets displayed on Swagger UI.
I also updated some internal documentation (a docstring) related to a function called by that endpoint.
Finally, I added some `TODO` comments related to telling the user what all the valid collection names are. We currently send them to the schema docs for that. We could, instead, implement an API endpoint that returns a list. That would allow us to refrain from giving the nuanced answer of "It's the names of the slots of the `Database` class, as long as those …
> Update `/nmdcschema/{collection_name}` API endpoint description to include performance-related guidance

- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_data/test_submission_portal_translator_data.yaml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Replace `# (issue)` below with a reference to the issue that this PR addresses, of the form `#\d+`. If merging this PR should close the issue, use `Fixes` or `Closes`. Then delete this paragraph.
Fixes # [1367](https://github.com/microbiomedata/nmdc-server/issues/1367)
A simple checklist of necessary activities that add …
> Add mapping for multiple environments

- nmdc_runtime/api/main.py
closes #742
In this branch, I used the Swagger UI's `onComplete` parameter to display bearer token info if present as a cookie (e.g. via ORCiD login).
Closes #742
...
I tested these changes by manual inspection of `http://127.0.0.1:8000/docs`
> Display copy-paste HTTP Authorization header with Bearer token on Swagger UI for ORCiD-Authenticated user

- nmdc_runtime/api/main.py
In this branch, I fixed a bug preventing ORCID Login from working.
I introduced the bug via one of the commits on PR #812, where I added a `//` JavaScript comment on a line above some JavaScript code, in a context where newlines were eventually stripped out. That stripping caused all those subsequent lines of code to effectively be commented out in the final JavaScript snippet.
Fixes #818 
I'll let GitHub Actions do that.
> Delete comment that impacted subsequent code once newlines were replaced

- requirements/dev.txt
- requirements/main.in
- requirements/main.txt
In this branch, I updated some Python packages in order to get some security patches.
I updated the `python-multipart` package specification in `main.in` to ensure the version that gets installed includes a security patch. This update was prompted by Dependabot alert 8; i.e. https://github.com/microbiomedata/nmdc-runtime/security/dependabot/8.
After updating that package, I synchronized the transitive dependencies and confirmed that `tornado` (which is a transitive dependency, not a direct one) was updated to version 6.4.2, which is what Dependabot recommended in its alert 7; i.e. https://github.com/microbiomedata/nmdc-runtime/security/dependabot/7.
- Fixes Dependabot alerts 7 and 8
- Makes Dependabot's PR #798 obsolete
- Makes Dependabot's PR #814 obsolete
Dependencies. I think a bunch …
> Update Python packages to patch security issues reported by Dependabot

- requirements/main.in
- requirements/main.txt
This branch does the routine `nmdc-schema` upgrade (to version 11.2.1) in advance of next week's release.
None
I tested these changes by ensuring `make up-dev` comes up successfully after doing the upgrade.
N/A
> Upgrade to `nmdc-schema` v11.2.1

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/translation/gold_translator.py
- tests/test_ops/test_gold_api_ops.py
In this PR, we are modifying the GOLD translator in such a way that it has the capability of ignoring/accepting the creation of field research sites based on a configuration parameter (`include_field_site_info`). By default it is set to `False` meaning it will not be created.
...
Required to finish these:
* https://github.com/microbiomedata/issues/issues/908
* https://github.com/microbiomedata/issues/issues/909
...
> Add option to GOLD translator to ignore field research sites

- nmdc_runtime/site/ops.py
- nmdc_runtime/util.py
- tests/test_ops/test_materialize_alldocs.py
In this branch, I updated materialize_alldocs in the dagster file.
In this PR, I:
- updated the "materialize_alldocs" in the dagster op to reflect functionality in bulk_validation_referential_integrity_check.ipynb 
- added necessary utils to utils.py
- replaced `pick` function to use `keyfilter` directly
- Related to #696 
I tested these changes by making sure the `ensure_alldocs` job runs in my local dagster environment: ![Succesful Dagster Run](https://github.com/user-attachments/assets/68d11c9e-9ff6-4731-8c27-55903d8bc01b)
> 696 update dagster op for materialize alldocs

- README.md
`export DOCKER_DEFAULT_PLATFORM=linux/amd64` was an older recommendation to allow amd64 containers to run on M1/M2 macs. However newer versions of Docker Desktop don't like this, and you should just let Docker pull the right container,
> Remove obsolete guidance from development guide

- metadata-translation/notebooks/data/changesheet-without-separator3.tsv
...
I tested these changes using changesheets:validate on runtime prod.
this is a documentation update
> Update changesheets examples

- .github/workflows/python-app.yml
In this branch, I updated a GitHub Actions workflow so that it is triggered by more events.
Specifically, I updated it so it is triggered by the event in which a file in the `data` directory (in which example changesheets reside) changes.
This is in an attempt to catch regression bugs at the PR stage, instead of allowing them to end up in `main`. A recent incident of a regression bug making it into `main` via a PR is when https://github.com/microbiomedata/nmdc-runtime/pull/841 was merged.
Fixes #843 
I did not test these changes locally. I will find out whether they suffice once they are merged into `main` and someone opens a PR that contains changes to the files in the newly-specified directory.
> Configure GHA to run tests when example changesheets change

- metadata-translation/notebooks/data/changesheet-without-separator3.tsv
In this branch, I removed a whitespace character from the ID column of an example changesheet.
The presence of that whitespace character made the changesheet invalid, from the perspective of the Runtime's changesheet validator.
Fixes #844 
I tested these changes by manually submitting the updated changesheet to https://api.microbiomedata.org/metadata/changesheets:validate and confirming that the Runtime considers the changesheet to be valid.
> Remove whitespace character that was making example changesheet invalid

- nmdc_runtime/api/endpoints/find.py
In this PR we are updating the logic for the `/data_objects/study/{study_id}` endpoint to use the newly renamed field name in `alldocs` called `_type_and_ancestors` (which previously used to be called `type`).
...
Fixes #850 
> Account for change in `alldocs` field name from `type` to `_type_and_ancestors`

- Makefile
- tests/test_api/test_endpoints.py
> [!NOTE]
> This branch is under construction.
In this branch, I implemented some pytest tests that exercise the core functionality of the `/data_objects/study/{study_id}` endpoint.
The tests do not currently exercise _all_ of the core functionality of that endpoint. I plan to hand this branch off to someone else to fill in the gaps (by following the "example" tests I have added here).
Eventually, this PR will fix #725.
I tested these changes by running `$ make test-run` on this branch, where the `test-run` Make target has been redefined locally as:
```make
test-run:
docker compose --file docker-compose.test.yml run test tests/test_api/test_endpoints.py
```
> Add tests targeting core functionality of `/data_objects/study/{study_id}` endpoint

- metadata-translation/notebooks/data/changesheet-without-separator3.tsv
In this branch, I add an example for multivalued string to the changesheets documenation
...
...
I tested these changes by using changesheets:validate
> Add multivalued string example to changesheets documentation

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repair/database_updater.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/resources.py
- nmdc_runtime/site/util.py
- nmdc_runtime/site/workspace.yaml
- tests/test_data/test_database_updater.py
We are trying to address the general problem of "database stitching" in this PR. It will often be the case that we have certain records in the database (say biosamples), but records that are needed for the next bits of processing of these "entities" might be missing.
For example, the first and most common use case that we are trying to address is filling in missing data_generation_set records for biosamples that have been brought into the database through the `SubmissionPortalTranslator` mechanism.
...
Fixes #756 https://github.com/microbiomedata/issues/issues/951 https://github.com/microbiomedata/issues/issues/813
> Add class with helper methods to fill in missing records in database

- nmdc_runtime/api/endpoints/metadata.py
- nmdc_runtime/util.py
- tests/test_the_util/test_the_util.py
On this branch, I fixed a bug where the real-time referential integrity checker in the `validate_json` function was ignoring documents that were already in the database.
On this branch, I changed the real-time referential integrity checker code to no longer use the `OverlayDB` class. When I first wrote the real-time referential integrity checker code, I had made an incorrect assumption about how the `OverlayDB` class worked.
Instead of it using the `OverlayDB` class, I updated the checker to use the real database directly and to use the JSON payload directly. Checking now happens in two stages (one for each of those potential "residences" of each referenced document).
The two stages are (in short—as a more detailed explanation is in the code comments):
1. Check the database
2. If the …
> Fix bug where `validate_json` referential integrity check ignored documents in database

- docs/nb/api_access_via_python.ipynb
On this branch, I consolidate two explanatory paragraphs in a Python notebook in an attempt to communicate an idea more clearly to readers.
N/A
Related to (already closed issue): #868 
I tested these changes by reading them back to myself.
> Clarify explanation of `access_token` property in Python notebook (in `docs/nb`)

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repair/database_updater.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/resources.py
- nmdc_runtime/site/translation/gold_translator.py
- nmdc_runtime/site/workspace.yaml
- tests/test_data/test_database_updater.py
This PR adds a Dagster job to create a `biosample_set` JSON (`Biosample` records) for those samples in a GOLD study that have been newly added since the previous time that we did an ingest for that study into NMDC.
...
Fixes https://github.com/microbiomedata/issues/issues/940
> Dagster job to populate missing biosample records for a study from GOLD

- nmdc_runtime/minter/config.py
On this branch, I changed how the minter gets typecodes from the schema.
Previously, the minter would use a locally-defined function (named `extract_typecode_from_pattern`) to extract typecodes from `id` slot patterns. That ran the risk of falling out of sync with how the same thing is done in the `nmdc-schema` package. On this branch, I deleted the locally-defined function and updated the calling code to call an equivalent function (named `get_typecode_for_future_ids`) provided by the `nmdc-schema` package.
Fixes #866 
I tested these changes by implementing a basic doctest and running it locally via:
```py
docker compose run --rm --no-deps fastapi sh -c 'pip install nmdc-schema==11.3.0 && python -m doctest -v nmdc_runtime/minter/config.py'
```
> Note: I included `pip install …
> Use `nmdc-schema`-provided function to get typecode from slot pattern

- nmdc_runtime/site/translation/gold_translator.py
In this branch, we update the pre-processing/filtering logic that filters out the biosamples and sequencing projects in the GOLD translator.
Details can be found in https://github.com/microbiomedata/issues/issues/1029
Fixes https://github.com/microbiomedata/issues/issues/1029
I tested these changes by generation JSON files for the various translators and exporters and comparing the counts and results to what we would expect from GOLD.
> Apply `projectStatus` filter only if `sequencingCenter` is JGI in GOLD translator

- nmdc_runtime/site/repository.py
- nmdc_runtime/site/translation/neon_surface_water_translator.py
- nmdc_runtime/site/workspace.yaml
The PR updates the code in the NEON surface water translator to account for creating `Manifest` / `manifest_set` records for samples that have been sequenced multiple times. It also pulls NEON data from the latest/provisional release to update/create new `DataGeneration` and `DataObject` records for samples that were "ignored" in the first ingest.
...
Fixes https://github.com/microbiomedata/issues/issues/1067
> Account for multiple sequencing runs in NEON surface water translator code

- nmdc_runtime/test.Dockerfile
Addresses #124 using pytest-cov by adding flag to the test runner (which is already a dev dependency in runtime)
> Add test coverage to pytest  

- nmdc_runtime/site/export/ncbi_xml.py
- nmdc_runtime/site/export/ncbi_xml_utils.py
- nmdc_runtime/site/ops.py
Fixes https://github.com/microbiomedata/issues/issues/1063
TODO:
On this branch, I...
...
...
> Replace the use of `alldocs` with respective collections for record retrieval in NCBI exporter

- nmdc_runtime/site/repair/database_updater.py
The `generate_biosample_set_from_gold_api_for_study` job in `data_records_stitching` _repository_ is responsible for creating a JSON file with biosamples of records from the GOLD study that are not already instantiated in the NMDC database. This takes as input the subsetted (do not exist in database) biosamples that need to be "processed" and pulls out certain attributes from it to populate slots on the `Biosample` class. Additionally, it also needs information about the associated sequencing projects and analysis projects from GOLD so it can comprehensively populate all the "mapped" slots on `Biosample` class.
...
Fixes https://github.com/microbiomedata/nmdc-runtime/issues/886
> Pass list of sequencing projects and analysis projects to `GoldStudyTranslator` call in `generate_biosample_set_from_gold_api_for_study`

- nmdc_runtime/api/endpoints/queries.py
On this branch, I fixed the syntax of an example JSON blob.
N/A
Fixes #932 
I'll wait for the GHA workflow to pass.
> Fix invalid syntax in user-facing API documentation

- nmdc_runtime/api/endpoints/metadata.py
- tests/test_api/test_endpoints.py
On this branch, I enabled referential integrity checking for the `/metadata/json:submit` API endpoint.
It's the same referential integrity checking that was enabled for the `/metadata/json:validate` API endpoint a few months ago, in Release 2025.1 (tag [v2.3.0](https://github.com/microbiomedata/nmdc-runtime/releases/tag/v2.3.0)).
I also added an automated **test** targeting the referential integrity check in the context of the `/metadata/json:submit` endpoint. It is currently the only test targeting the endpoint.
I also added a `TODO` comment about testing other aspects of the endpoint.
Fixes #954 
I added an automated test that targets the new functionality, and confirmed it passes locally and on GHA.
> Enable referential integrity checking for `/metadata/json:submit` API endpoint

- Makefile
On this branch, I fix #956 with a change to one line.
NERSC's `sshproxy` helper is now a binary, not a bash shell script.
Fixes #956
I tested these changes by running `make nersc-sshproxy`
> Fix `nersc-sshproxy` Make target body

- Makefile
On this branch, I add the `--no-perms` flag to the `rsync` invocation in the `mongorestore-nmdc-db` `make` target. 
There is no need for `rsync` to attempt to set permissions in this context.
Fixes #958 
I tested these changes by running `make mongorestore-nmdc-db`.
> Add `--no-perms` flag to `rsync` invocation in `make mongorestore-nmdc-db`

- db/migrations/notebooks/migrate_11_4_0_to_11_5_0.ipynb
- db/migrations/notebooks/migrate_11_5_0_to_11_5_1.ipynb
- db/migrations/notebooks/migrate_11_5_1_to_11_6_0.ipynb
On this branch, I implemented a notebook that can be used to migrate the Mongo database from being compliant with schema version 11.5.1 to being compliant with schema version 11.6.0.
Here's a link to the "rendered" notebook on this branch (may be easier to review than the raw JSON):
- https://github.com/microbiomedata/nmdc-runtime/blob/952-implement-python-notebook-for-migrating-from-schema-version-1151-to-1160/db/migrations/notebooks/migrate_11_5_1_to_11_6_0.ipynb
I also created a couple of "no op" notebooks related to recent schema version jumps.
Fixes #952 
I ran the [unique parts of] the notebook locally. I confirmed both of the migrators (imported from `nmdc-schema`) ran and the resulting documents were valid with respect to schema 11.6.0.
> Implement notebook for migrating database from schema version `11.5.1` to `11.6.0`

- nmdc_runtime/api/endpoints/jobs.py
- nmdc_runtime/api/models/job.py
- nmdc_runtime/api/models/operation.py
- tests/test_api/test_endpoints.py
On this branch, I add a `POST /jobs/{job_id}:release` endpoint that:
- cancels the (authenticated) requesting `site`'s `claims` for a `job`, i.e. marks `operations` identified by `op_id` in the job's claims array as `cancelled`
- updates the contents of job's document-local claims array to reflect the cancellation (aka release) of these claims.
Executes a MongoDB transaction to ensure atomic change of the job document along with the relevant set of operations documents.
Closes #951
I tested these changes by adding `test_release_job` to `tests/test_api/test_endpoints.py`.
> Create "release jobs" endpoint

- nmdc_runtime/api/endpoints/workflows.py
- tests/lib/faker.py
- tests/test_api/test_endpoints.py
On this branch, I added referential integrity checking to the request validation performed by the `POST /workflows/workflow_executions` API endpoint.
I also added a test that targets this referential integrity checking, and updated the existing test so that it would no longer insert a document having broken references. Indeed, most of the changed lines on this branch are test-related.
Fixes #960 
I tested these changes by ensuring the newly-added test passes locally.
> Add referential integrity check to `POST /workflows/workflow_executions` API endpoint

- nmdc_runtime/api/main.py
- nmdc_runtime/api/models/util.py
On this branch, I updated the Runtime's bootup code so that it would ensure that MongoDB indexes exist on the `has_input` and `has_output` fields in the `workflow_execution_set` collection.
I also added a `TODO` comment about removing code related to an obsolete collection. Finally, I added a docstring to a function that lacked one.
Note: I made a typo (i.e. "createrd" instead of "create") in the commit message.
Fixes #971 
I manually created the `has_output` index in the MongoDB database (both in the development environment and the production environment) via Studio 3T as part of a recent urgent task and found that it drastically sped up [this aggregation query](https://github.com/microbiomedata/issues/issues/1159#issuecomment-2831521710).
I did not test the creation of the `has_input` …
> Create indexes on `has_input`/`has_output` in `workflow_execution_set`

- requirements/main.in
- requirements/main.txt
- tests/test_the_util/test_the_util.py
On this branch, I implemented a test **demonstrating** how someone can determine whether changes to the database being made via a transaction would introduce a referential integrity violation, and then abort the transaction if they would.
Specifically, in the test, I create two studies—one that is `part_of` the other—and then I start a transaction. In the transaction, I "stage" the deletion of the _referenced_ study and perform a referential integrity check. Finally, when I see that there is a referential integrity violation, I abort the transaction and confirm the referenced study did not really get deleted.
I also updated the `refscan` package to a version that supports transactions. It was released earlier today.
Fixes #974 
I tested these changes by running the following sequence of …
> Add test showing referential integrity check during pending transaction

- nmdc_runtime/api/endpoints/queries.py
- tests/test_api/test_endpoints.py
On this branch, I edited /queries:run to check if a user trying to aggregate has the correct permissions. 
...
Fixes #970 
I tested these changes by running them locally and confirming they all pass.
> Update `/queries:run` API endpoint so only users having specific allowance can run aggregation command

- nmdc_runtime/api/endpoints/queries.py
- requirements/main.in
- requirements/main.txt
- tests/test_api/test_endpoints.py
On this branch, I added a real-time referential integrity check to the `POST /queries:run` API endpoint; specifically, to a branch of code that handles the "delete" command.
Before, the endpoint allowed users to delete documents that other documents referred to, even when those other documents were not also being deleted as part of the same request. When that happens, it leaves behind "broken references" in the database.
Now (in this PR), the endpoint disallows that. If the user tries to delete a document that other documents reference, and those other documents aren't also being deleted as part of the same request, the endpoint returns an HTTP 422 response and does not perform any deletions.
I updated the `refscan` package version (a dependency of the Runtime) from `0.2.4` to `0.2.5` so …
> Add referential integrity check to "delete" command of `POST /queries:run` API endpoint

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
On this branch, I updated the two Dagster graphs that include the `materialize_alldocs` op, so that Dagster will not run the `materialize_alldocs` op until the "previous" op has finished running.
Here's one of those graphs on `main` (notice there is no "dependency" line connected to the `materialize_alldocs` op):
Here's the same graph on this branch (notice the new "dependency" line):
Fixes #1011 
I tested these changes by confirming that, on Dagit, the two affected graphs look the way I expect. I also tested the changes by confirming the GHA checks (including tests) all pass.
> Configure Dagster run `materialize_alldocs` op only after its dependent ops have finished 

- nmdc_runtime/api/endpoints/queries.py
- tests/test_api/test_endpoints.py
On this branch, I made it so the `/queries:run` endpoint once again allows deletions that leave behind broken references.
I expect this change to be temporary. It is necessary in the short term, because of the "catch-22" situation described in #1021.
Fixes #1021
I tested these changes by running `make test` locally and confirming all tests pass. Note that I disabled a test that depends upon these kinds of deletions being rejected. I expect that test to eventually be reenabled.
> Update `/queries:run` to allow deletions that leave behind broken references

- nmdc_runtime/api/endpoints/find.py
- tests/test_api/test_endpoints.py
On this branch, I updated the `/workflow_executions/{id}/related_resources` API endpoint's response so that, in addition to including resources _related_ to the specified `workflow_execution_set` document, it also includes the specified `workflow_execution_set` document, itself.
I also standardized names of tests and fixed a typo in the name of a test.
Fixes #995
I tested these changes by running `make test` locally and confirming all tests pass, including the tests that target the endpoint I made changes to in this PR.
> Update `related_resources` API response to include subject `workflow_execution_set` document

- tests/lib/faker.py
- tests/test_api/test_endpoints.py
On this branch, I updated the methods of the `Faker` class so they validate the documents they generate, before returning them. They delegate the validation to the Pydantic models, so the validation is subject to whatever caveats apply (some are listed in a `Note:` comment in the diff).
I think this change will decrease the likelihood that the methods fall out of sync with the schema.
Fixes #1026 
This is related to the test suite.
I tested these changes by (a) confirmed their existing doctests still pass and (b) adding new doctests and confirmed _those_ also pass.
> Update `Faker` methods to validate documents before returning them

- nmdc_runtime/api/endpoints/nmdcschema.py
- nmdc_runtime/config.py
- nmdc_runtime/util.py
- tests/test_api/test_endpoints.py
- tests/test_the_util/test_the_util.py
On this branch, I disabled the "preliminary" `/nmdcschema/related_ids` endpoint and the tests that target it.
As discussed during today's infrastructure meeting, we will omit the endpoint (which has never been deployed to production before) from the upcoming production release, and then promptly reintroduce it back into the development environment. 
I disabled the endpoint and tests without commenting them out (which would have affected the commented lines' Git history) and without wrapping them in `if False:` blocks (which, similarly, would have affected their Git history due to the intending).
This branch introduces a new decorator named `@decorate_if`, which can be used to conditionally  decorate a function.
FYI: @aclum and @kheal
Fixes #1031 
I tested these changes by confirming all …
> Implement "on/off" switch for `/nmdcschema/related_ids` endpoint (and turn it "off")

- nmdc_runtime/api/main.py
- nmdc_runtime/api/openapi.py
- nmdc_runtime/api/swagger_ui/assets/script.js
- nmdc_runtime/api/swagger_ui/assets/style.css
On this branch, I extracted several things related to OpenAPI from the `nmdc_runtime/api/main.py` file into other files. This was in an attempt to make the OpenAPI aspects of the code base easier for people to maintain.
Specifically, I:
- Extracted the tag descriptions and tag order specifier into a separate Python module, `openapi.py`
- Extracted the API description into that same Python module, `openapi.py`
- Extracted a literal CSS snippet into a new CSS file, `style.css`
- Extracted a literal JavaScript snippet into a new JS file, `script.js`
There are other JavaScript snippets in `main.py` which I did not extract. The reason I haven't extracted those yet is that there is a custom quote conversion happening with them that I didn't want to get into today.
The …
> Make it easier to maintain Swagger/OpenAPI tags

- nmdc_runtime/api/main.py
On this branch, I updated the version of Swagger UI that the Runtime uses, from 5.9.0 (released in 2023) to [5.25.4](https://github.com/swagger-api/swagger-ui/releases/tag/v5.25.4) (released today).
None.
Fixes #1040 
I tested these changes by:
- Visiting Swagger UI in my local development environment
- Confirming the web browser fetched the JS and CSS files from the new URLs
- Confirming I could log in and out (both via ORCID and not via ORCID)
- Confirming I could access public and private API endpoints via "Try it out"
- Confirming the custom JavaScript/CSS (related to the `Bearer` token box) still works
I don't think this change warrants any documentation changes on our part.
> Unpin Swagger UI version so the Runtime always uses the latest version

- nmdc_runtime/api/endpoints/find.py
- tests/test_api/test_endpoints.py
On this branch, we updated the `/data_objects/study/{study_id}` endpoint to accommodate some recent changes to the `alldocs` collection (a cache-like collection that is not described by the schema), refactored the tests that targeted the endpoint, and added more such tests (including one that reproduces a previously-failing-now-working scenario).
The "refactoring" involved replacing literal dictionaries with invocations of `Faker` methods, and encapsulating all the tests into a common class.
#1049 
We tested these changes by confirming `make test` passes locally and the tests all pass when run by GHA.
> Fix bug where `/data_objects/study/{study_id}` does not return all related data objects

- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_data/data/nucleotide_sequencing_mapping_output.yaml
- tests/test_data/data/plant_air_jgi_output.yaml
- tests/test_data/data/sequencing_data_input.yaml
- tests/test_data/data/sequencing_data_output.yaml
On this branch, I updated the submission data translator to handle cases where the submission schema has an implicit unit on a slot.
The submission schema enforces a pattern like `{number}` or `{number} - {number}` on the `depth` slot, and it instructs the user (via the slot title and description) that the numbers should have unit meters. This runs counter to the submission data translator's existing logic of expecting to be able to extract a unit from the raw value provided by the user (i.e. something like `{number} {unit}`. The fix here to handle `depth` a special case where we will always set the `has_unit` value to `m`. 
Fixes #1048 
Fixes https://github.com/microbiomedata/issues/issues/236
The special casing introduced here should be able to be removed after …
> Add depth units when translating submission records

- nmdc_runtime/api/main.py
- tests/test_api/test_main.py
On this branch, I update the ensure_default_api_perms function so it ensures the admin user has aggregation permission
Fixes #1035.
> Update `ensure_default_api_perms` function to include aggregation permission

- nmdc_runtime/api/main.py
- nmdc_runtime/api/models/util.py
On this branch, I update the Runtime's boot-up code to ensure that the `type` field of every schema-described collection is indexed.
Here's a screenshot showing the newly-created index in the `functional_annotation_agg` collection in my local Runtime development environment.
None.
This will help speed up the queries involved in #1087. I do not know whether it will be enough to the timeouts, though.
I tested these changes by — in my local Runtime development environment — (a) confirming the `type` field was not indexed on the `functional_annotation_agg` collection, (b) restarting the FastAPI app, (c) confirming the `type` field _was_ indexed on that collection (as shown in the screenshot above), and (d) restarting the FastAPI app again to confirm that the code didn't lead to any "error: …
> Index `type` field to speed up Mongo queries involving it

- nmdc_runtime/api/endpoints/find.py
- tests/test_api/test_endpoints.py
On this branch, I updated the API endpoint to return `Biosample`s related to a `WorkflowExecution` through _any_ `DataGeneration`s that inform that `WorkflowExecution`, as opposed to only one of the `DataGeneration`s that informs it.
To do that, I took a TDD approach: I first implemented a test demonstrating that (on `main`), when a `WorkflowExecution` "was informed by" two `DataGeneration`s, the API response only included the `Biosample` associated with _one_ of those `DataGeneration`s. Then, I updated the endpoint so that its response includes both `Biosample`s.
I also updated the endpoint's description to reflect the fact that its response payload does _not_ include `DataGeneration`s.
Fixes #1083 
I tested these changes by implementing a test demonstrating the bug. The test failed …
> Update `related_resources` endpoint to account for multiple `DataGeneration`s informing a `WorkflowExecution`

- db/migrations/ad_hoc_scripts/migrate_jobs_collection_from_schema_11.8.0_to_11.9.1.mongosh.js
On this branch, I updated a `filter` in an ad hoc migration script (which was run in production on Monday, July 28, 2025, as part of [Release 2025.7](https://github.com/microbiomedata/issues/issues/1263)). I updated the `filter` so that it no longer matches documents whose `config.was_informed_by` field consists of a list. This way, the final debug statement will produce a count of `0`, which will match the stated expectation.
None.
None.
I tested these changes by running the updated script in my local development environment.
```js
db.jobs.countDocuments({});
// -> 27060
db.jobs.countDocuments({ 
"config.was_informed_by": { 
$type: "string",
$not: { $type: "array" }
}
});
// -> 23380
db.jobs.countDocuments({ 
"config.was_informed_by": { 
$type: "string",
}
});
// -> 23380
const filter = …
```
> Update `filter` in ad hoc Mongo migration script to exclude irrelevant documents

- nmdc_runtime/api/core/util.py
- nmdc_runtime/api/endpoints/find.py
- nmdc_runtime/api/endpoints/queries.py
- nmdc_runtime/api/models/object.py
- nmdc_runtime/lib/nmdc_dataframes.py
- tests/test_data/test_translator.py
On this branch, I fixed various issues about which pytest displays warnings. I fixed all such issues over which we have direct control.
Pytest continues to warn about some issues in upstream packages (e.g. `pydantic`, `sssom_schema`, `eutils`).
Fixes #1110 
I tested these changes by checking the list of warnings pytest displays when the tests runs, and confirming that the only remaining ones are from `site-packages`.
<details>
<summary>Show/hide remaining warnings</summary>
```py
================================================================================================================== warnings summary ==================================================================================================================
../usr/local/lib/python3.10/site-packages/linkml/generators/pydantic …
```
> Fix miscellaneous issues about which pytest displays warnings

- nmdc_runtime/api/endpoints/jobs.py
On this branch, I updated the user-facing documentation (visible on Swagger UI) of the `/jobs/{job_id}:release` endpoint, in an attempt to make it more clear to users what is happening (especially, what the word `site` is referring to).
| Before | After |
| --- | --- |
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/7cd8b5e3-5d61-4ee0-b5e1-cd6778cfbd71" /> | <img width="400" alt="image" src="https://github.com/user-attachments/assets/7e1a08df-a33a-4b92-80db-77d82ee96b82" /> |
I think someone more familiar with jobs and claims would be able to make the endpoint's documentation even more clear. I consider this to be an improvement, though.
I also moved the return type "hint" from the FastAPI router decorator to the standard Python function return type hint …
> Clarify user-facing documentation for `/jobs/{job_id}:release` endpoint

- nmdc_runtime/api/core/idgen.py
- nmdc_runtime/api/endpoints/util.py
On this branch, I updated the `generate_ids` function so that, instead of invoking `collection.count_documents({})`, it invokes `collection.estimated_document_count({})`. This sped up ID generation by about 200x.
I also added some `TODO` comments about documentation and about another performance optimization opportunity. 
Fixes #1160
See [linked issue](https://github.com/microbiomedata/nmdc-runtime/issues/1160#issuecomment-3213071851) for load testing and performance profiling screenshots.
> Replace slow MongoDB query with faster alternative (in `generate_ids` function)

- docker-compose.yml
- nmdc_runtime/api/endpoints/util.py
- tests/test_api/test_endpoints_util.py
- util/load_testing/README.md
- util/load_testing/locustfile.py
On this branch, I updated the `list_resources` function so that, instead of counting _all_ matching documents in a collection, it only counts _the minimum number necessary_ in order to do its job.
Here's an analogy:
I have a yard with lots of different types of trees in it. I want to know whether my yard has **more than 3** oak trees. I can either:
1. (the old way) Ask someone to **count all** the oak trees in my yard, and tell me that number (I'll compare it with 3); or
2. (the new way) Ask someone to **count up to 4** oak trees in my yard, and tell me that number (I'll compare it with 3)
As a result, the `GET /nmdc_schema/{collection_name}` endpoint (and other endpoints and functions that use the `list_resources` function under the hood) is faster. See load testing results and …
> Speed up `list_resources` function for large collections

- nmdc_runtime/site/ops.py
- nmdc_runtime/site/resources.py
- nmdc_runtime/util.py
On this branch, I fixed a bug affecting both the `POST /metadata/json:submit` endpoint and the `POST /workflows/workflow_executions` endpoint.
The `add_docs` function invokes `pymongo`'s `bulk_write` method once per collection specified in its `docs` parameter. To that `bulk_write` method, it passes a list of operations, each one corresponding to a document in that collection (in the `docs` parameter). When there _are_ no documents in that collection (in the `docs` parameter), it passes a list of 0 operations. When `bulk_write` receives 0 operations, it raises an exception. 
The changes on this branch prevent the invocation of the `bulk_write` method in that situation.
On this branch, I also added a `TODO: Document this function.` comment to several undocumented functions that I stepped …
> Avoid invoking `bulk_write` with no operations

- nmdc_runtime/site/graphs.py
- nmdc_runtime/site/ops.py
- nmdc_runtime/site/repository.py
- nmdc_runtime/site/translation/submission_portal_translator.py
- tests/test_graphs/test_submission_portal_graphs.py
This branch adds an optional config setting for Study ID for ingesting portal submissions.
Previously a new study ID was always minted. If a valid study ID is supplied, that ID will be used for the ingestion of the portal submission.
On error/invalid ID given an error is thrown.
This PR resolves https://github.com/microbiomedata/nmdc-runtime/issues/1141
I manually tested this change by providing an ID in the config, which was accepted. I did the same with an invalid ID which (should throw an error after review and figuring out exactly what to do, but the current logic for catching bad IDs works) which minted a new ID. And I tried a case where no ID was supplied which resulted in expected behavior of minting a new ID.
> Add optional study ID input to tie submissions to one study

- nmdc_runtime/api/swagger_ui/assets/script.js
On this branch, I made it so, on Swagger UI, when the user clicks on the "Authorize" button, the web browser's focus is on the "Username" field at the top of the modal.
Previously, the web browser's focus was on the "bearer" field at the bottom of the modal—resulting in some users not realizing there _was_ a user login field higher up in the modal.
Fixes #1181
Swagger UI.
I tested these changes by manually clicking the "Authorize" button and observing that the focus was on the "Username" field.
> Update Swagger UI authorization modal to focus on "Username" field when opened

- docs/content/howto-guides/minting-ids.md
- nmdc_runtime/api/main.py
- nmdc_runtime/api/swagger_ui/assets/style.css
On this branch, I...
- Configured Swagger UI to keep the user logged in across page refreshes
- Hid the scope definitions that appeared atop the login forms (here's a before-and-after)
- Updated user-facing documentation to reflect the recently-customized login form header text (the customizations were made in https://github.com/microbiomedata/nmdc-runtime/pull/1064)
N/A
Fixes #1151 
Swagger UI only.
I tested these changes by confirming that, when I'm logged into a native Runtime account and I reload the Swagger UI page, I am still logged in after the page has reloaded.
> Configure Swagger UI to persist auth status and simplify login form

- nmdc_runtime/api/endpoints/util.py
- nmdc_runtime/api/models/util.py
On this branch, I updated the user-facing documentation of the `page` (a.k.a. "page number") request parameter (used on the `find` endpoints) so that it says that page number-based pagination cannot be used to access resources beyond the first 10,000.
Previously, this limitation was only communicated when the user _tried_ to access a resource _beyond_ that threshold (at which point, the API would return an error telling them about the limitation).
Here's a screenshot showing how the new `page` documentation differs from what it is on `main`:
Fixes #934
I tested these changes by confirming the description on Swagger UI looks the way I expected.
> Document that page number-based pagination only provides access to first 10,000 resources

- docker-compose.test.yml
- docker-compose.yml
On this branch, I configured Docker Compose to attach a pseudo-TTY to the `fastapi` container. As a result, the container logs will appear in color (in local development) instead of monochrome.
Here's a before-and-after screenshot of the `fastapi` container logs:
Before:
After:
Fixes #1217 
Container logs in local development.
I tested these changes by confirming the container logs appear in color when `tty: true` is set, and appear monochrome when it is not set. I went back and forth a few times to confirm.
> Make it so `fastapi` console output is in color in local environment

- Makefile
Fixes a regression from commit 5d56571b2602306ce61bff65eb0f40108bfd6745 in which a hard-coded port number was changed from 27018 (the default value of `DEV_STACK_HOST_MACHINE_PORT_MONGO` set in `.env.example`) to 59639.
Fix is to explicitly use the value set by `DEV_STACK_HOST_MACHINE_PORT_MONGO` in `.env`, i.e. the locally mapped port for the `mongo` service in `docker-compose.yml`.
Fixes #1223
Restricted to `Makefile` target for local `mongorestore` from a remote mongodump.
Via `make mongorestore-nmdc-db`. I also manually determined that absence of `DEV_STACK_HOST_MACHINE_PORT_MONGO` in `.env` does not impact execution of other `Makefile` targets.
No documentation changes needed.
> Fix regression (change of hard-coded `mongorestore` port) in Makefile

- db/migrations/notebooks/migrate_11_10_0_to_11_11_1.ipynb
- pyproject.toml
- uv.lock
On this branch, I implemented a Python notebook that can be used to migrate the Mongo database from conforming to schema 11.10.0 to conforming to schema 11.11.1.
The schema, itself, did not change between schema versions 11.11.0 and 11.11.1. The schema did, however, change between schema versions 11.10.0 and 11.11.0.
Fixes #1230
I tested these changes by migrating the dev Mongo database.
> Implement Python notebook that migrates Mongo database from schema `11.10.0` to `11.11.1`

- nmdc_runtime/api/endpoints/queries.py
On this branch, I updated the user-facing examples above the `/queries:run` endpoint on Swagger UI, so that they would include an example involving a join across two collections.
Here's what the newly-added example looks like on the rendered Swagger UI page:
Fixes #1134 
Documentation on the Swagger UI page.
I tested these changes by submitting the example request payload in the dev environment; once with the Study `id` shown, and once with a different Study `id`.
> Add `/queries:run` example demonstrating a join across two collections

- .github/workflows/release-to-pypi.yml
On this branch, I updated a GHA workflow to use a stable version of a [third-party action](https://github.com/pypa/gh-action-pypi-publish). I expect this to make it so the GHA workflow can once again publish the `nmdc-runtime` package to PyPI.
I don't know why I changed it to the non-stable version to begin with. I did it as part of a [commit](https://github.com/microbiomedata/nmdc-runtime/commit/2373a190995659b887e346c0404b9f591d15baf8) where I was undoing some changes I had temporarily made on a branch, in order to clean up the diff for the eventual PR reviewers. 
I don't know why I edited this line (regardless of what I edited it _to_) from its original value. I assume I got mixed up between different GHA workflow files that I was dealing with, and copy/pasted from the wrong source …
> Fix issue preventing GHA workflow from publishing to PyPI

- .github/workflows/mkdocs.yml
- Makefile
- docker-compose.yml
- docs/content/contributing-docs.md
- nmdc_runtime/Dockerfile
- nmdc_runtime/site/entrypoint-daemon.sh
- nmdc_runtime/site/entrypoint-dagit-readonly.sh
- nmdc_runtime/site/entrypoint-dagit.sh
On this hotfix branch—which is based upon tag `v2.11.0`—I made changes to the way uv syncs dependencies and runs applications (e.g. uvicorn, black).
On this branch, here's what the `fastapi` container logs show when the container first starts up:
```console
2025-10-02 19:23:42.465 | INFO:     Will watch for changes in these directories: ['/code']
2025-10-02 19:23:42.465 | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2025-10-02 19:23:42.465 | INFO:     Started reloader process [10] using WatchFiles
2025-10-02 19:23:51.163 | INFO:     Started server process [12]
2025-10-02 19:23:51.163 | INFO:     Waiting for application startup.
2025-10-02 19:23:51.765 | Identifying schema-allowed references.
2025-10-02 19:23:52.312 | INFO:     Application startup complete.
``` …
> Hotfix: Prevent uv from installing dependencies when running application
